/**
 * Banco de questões do quiz de bancada — 20 por tema da roda de tipos.
 *
 * Fonte para o seed (`npm run db:seed-quiz`); em runtime o servidor lê da
 * tabela `quiz_questions`, nunca deste arquivo. O enunciado é a chave: mudar o
 * texto cria uma questão nova, mudar as alternativas atualiza a existente.
 *
 * Cada tema tem 8 fáceis, 6 médias e 6 difíceis — a proporção 4:3:3 que o
 * sorteio usa como peso (ver `QUIZ_DIFFICULTY_MIX`). O tamanho não é estético:
 * o aluno nunca recebe uma questão que já respondeu no tema enquanto houver
 * inédita, e com 10 por tema quem passava o dia no estande esgotava o banco
 * antes do fim do evento.
 *
 * A ordem das alternativas aqui é só a de cadastro — o servidor embaralha a
 * cada aplicação, senão a fila da bancada decoraria a posição da resposta.
 */

export type QuizDifficulty = 'facil' | 'media' | 'dificil';

export interface QuizSeedQuestion {
  theme: string;
  difficulty: QuizDifficulty;
  prompt: string;
  options: string[];
  /** Índice da alternativa correta em `options`. */
  answer: number;
}

export const QUIZ_QUESTIONS: QuizSeedQuestion[] = [
  // ── Humanas ───────────────────────────────────────────────────────────────────
  // Humanas aqui é humanas APLICADA à computação: ética, LGPD, impacto social e
  // método científico. Pergunta de gramática ou literatura não entra — o aluno
  // que acertar vai capturar um professor da roda, não fazer prova de redação.
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'A LGPD é a lei brasileira que trata de quê?',
    options: [
      'Proteção de dados pessoais',
      'Direitos autorais de software',
      'Crimes de invasão de sistemas',
      'Acessibilidade em sites públicos',
    ],
    answer: 0,
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'O que a LGPD considera um "dado pessoal"?',
    options: [
      'Qualquer informação de uma empresa',
      'Informação que identifica ou pode identificar uma pessoa',
      'Apenas CPF e RG',
      'Apenas dados guardados em nuvem',
    ],
    answer: 1,
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt:
      'Ao coletar dados num cadastro, a LGPD exige que o usuário saiba principalmente o quê?',
    options: [
      'A linguagem de programação usada',
      'O nome do servidor onde os dados ficam',
      'A finalidade para a qual os dados serão usados',
      'O custo do sistema',
    ],
    answer: 2,
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'O que caracteriza plágio num trabalho acadêmico?',
    options: [
      'Citar um autor indicando a fonte',
      'Apresentar ideia ou texto de outra pessoa como se fosse seu',
      'Usar mais de uma referência bibliográfica',
      'Escrever em primeira pessoa',
    ],
    answer: 1,
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt:
      'Um aplicativo de lanterna pede acesso à agenda de contatos. Que princípio da LGPD isso contraria?',
    options: [
      'Minimização: coletar apenas o necessário',
      'Portabilidade dos dados',
      'Irretroatividade da lei',
      'Livre iniciativa',
    ],
    answer: 0,
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'O que é viés algorítmico?',
    options: [
      'Erro de sintaxe que trava o programa',
      'Lentidão do sistema sob carga alta',
      'Quando o sistema reproduz desigualdades presentes nos dados',
      'Falha de conexão com o banco de dados',
    ],
    answer: 2,
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'O que define um software livre?',
    options: [
      'Ser distribuído sem custo',
      'Permitir usar, estudar, modificar e redistribuir o código',
      'Rodar apenas em Linux',
      'Não ter nenhuma licença',
    ],
    answer: 1,
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'Numa pesquisa com pessoas, o que é consentimento informado?',
    options: [
      'A pessoa concorda depois de entender objetivos e riscos',
      'O pesquisador avisa a universidade',
      'Um contrato assinado pelo orientador',
      'A autorização do comitê de informática',
    ],
    answer: 0,
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt: 'Na LGPD, quem é o "titular" dos dados?',
    options: [
      'A empresa que armazena os dados',
      'O desenvolvedor do sistema',
      'A pessoa a quem os dados se referem',
      'A autoridade nacional de proteção de dados',
    ],
    answer: 2,
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt: 'Qual é a diferença entre controlador e operador na LGPD?',
    options: [
      'O controlador decide sobre o tratamento; o operador o executa em nome dele',
      'O controlador é sempre uma pessoa física',
      'O operador responde sozinho por qualquer vazamento',
      'Não há diferença: são sinônimos na lei',
    ],
    answer: 0,
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt: 'O que busca a acessibilidade digital?',
    options: [
      'Reduzir o custo de hospedagem do site',
      'Garantir que pessoas com deficiência consigam usar o sistema',
      'Aumentar a velocidade de carregamento',
      'Bloquear acesso de fora do país',
    ],
    answer: 1,
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt:
      'Um sistema de reconhecimento facial erra bem mais em pessoas negras. Qual é a causa mais provável?',
    options: [
      'Resolução baixa da câmera',
      'Base de treino pouco representativa',
      'Excesso de memória RAM no servidor',
      'Uso de uma linguagem de programação antiga',
    ],
    answer: 1,
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt: 'O que o termo "exclusão digital" descreve?',
    options: [
      'A remoção definitiva de uma conta de usuário',
      'O apagamento de dados após o prazo legal',
      'A desigualdade de acesso a tecnologia e conectividade',
      'O bloqueio de sites por ordem judicial',
    ],
    answer: 2,
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt: 'Para que serve a revisão por pares na ciência?',
    options: [
      'Especialistas avaliam método e resultados antes da publicação',
      'O autor revisa o próprio texto antes de enviar',
      'A revista corrige a ortografia do artigo',
      'O orientador assina o trabalho do aluno',
    ],
    answer: 0,
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt:
      'A LGPD garante ao titular um direito específico diante de decisões tomadas apenas por algoritmo. Qual?',
    options: [
      'Receber uma cópia do código-fonte',
      'Solicitar a revisão da decisão automatizada',
      'Proibir o uso de IA pela empresa',
      'Exigir indenização automática',
    ],
    answer: 1,
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt: 'O que significa anonimizar um dado, segundo a LGPD?',
    options: [
      'Guardá-lo criptografado no banco',
      'Trocar o nome do titular por um apelido',
      'Fazer com que ele perca a possibilidade de associação a um indivíduo',
      'Mantê-lo acessível só para administradores',
    ],
    answer: 2,
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt:
      'Uma loja virtual precisa do CPF do cliente para emitir nota fiscal. Qual base legal da LGPD sustenta esse tratamento?',
    options: [
      'Cumprimento de obrigação legal',
      'Consentimento revogável a qualquer momento',
      'Proteção do crédito',
      'Interesse público na área da saúde',
    ],
    answer: 0,
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt:
      'Por que o "dilema do bonde" reaparece na discussão sobre carros autônomos?',
    options: [
      'Porque o carro precisa calcular a rota mais curta',
      'Porque obriga a decidir de antemão quem será preservado numa colisão inevitável',
      'Porque trens e carros compartilham trilhos',
      'Porque define o limite de velocidade do veículo',
    ],
    answer: 1,
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt:
      'Segundo o critério de falseabilidade de Popper, o que uma hipótese científica precisa permitir?',
    options: [
      'Ser confirmada por pelo menos três experimentos',
      'Ser aceita pela maioria dos pesquisadores da área',
      'Ser refutada por alguma observação possível',
      'Ser expressa em fórmula matemática',
    ],
    answer: 2,
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt: 'O que propõe a abordagem "privacy by design"?',
    options: [
      'Tratar privacidade desde a concepção do sistema, e não como ajuste posterior',
      'Deixar o usuário configurar a privacidade no primeiro acesso',
      'Publicar a política de privacidade na página inicial',
      'Armazenar dados somente em servidores nacionais',
    ],
    answer: 0,
  },

  // ── Matemática ────────────────────────────────────────────────────────────────
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de f(x) = x²?',
    options: ['x', '2x', 'x²/2', '2'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Quanto vale o limite de (3x + 1) quando x tende a 2?',
    options: ['5', '6', '7', '9'],
    answer: 2,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de uma função constante?',
    options: ['A própria constante', '0', '1', 'x'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a integral indefinida de 2x dx?',
    options: ['x² + C', '2x² + C', 'x + C', '2 + C'],
    answer: 0,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Qual é a derivada de sen(x)?',
    options: ['-sen(x)', 'cos(x)', '-cos(x)', 'tg(x)'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Quanto vale o limite de sen(x)/x quando x tende a 0?',
    options: ['0', '1', 'Infinito', 'Não existe'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Pela regra do produto, a derivada de f(x)·g(x) é:',
    options: [
      "f'(x)·g'(x)",
      "f'(x)·g(x) + f(x)·g'(x)",
      "f'(x)·g(x) - f(x)·g'(x)",
      "f(x)·g'(x)",
    ],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Qual é a derivada de e^(2x)?',
    options: ['e^(2x)', '2e^(2x)', '2x·e^(2x)', 'e^(2x)/2'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'A função f(x) = x³ - 3x tem mínimo local em qual ponto?',
    options: ['x = -1', 'x = 0', 'x = 1', 'x = 3'],
    answer: 2,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Quanto vale a integral de x² dx no intervalo de 0 a 1?',
    options: ['1/4', '1/3', '1/2', '1'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de f(x) = 5x?',
    options: ['0', '5', '5x', 'x'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Pela regra da potência, qual é a derivada de f(x) = x³?',
    options: ['3x', 'x²', '3x²', '3x³'],
    answer: 2,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Quanto vale o limite de x² quando x tende a 3?',
    options: ['3', '6', '9', 'Não existe'],
    answer: 2,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a integral indefinida de dx?',
    options: ['0 + C', 'x + C', 'x²/2 + C', '1/x + C'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Qual é a derivada de cos(x)?',
    options: ['sen(x)', '-sen(x)', 'cos(x)', '-cos(x)'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Qual é a derivada de ln(x), para x > 0?',
    options: ['1/x', 'ln(x)/x', 'x·ln(x)', 'e^x'],
    answer: 0,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Pela regra da cadeia, como se calcula a derivada de f(g(x))?',
    options: ["f'(x) · g'(x)", "f'(g(x)) · g'(x)", "f'(g'(x))", "f(g'(x))"],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Qual é a integral indefinida de 1/x dx, para x > 0?',
    options: ['ln(x) + C', '1/x² + C', '-1/x² + C', 'x·ln(x) + C'],
    answer: 0,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Pela regra do quociente, a derivada de f(x)/g(x) é:',
    options: [
      "(f'·g + f·g') / g²",
      "f' / g'",
      "(f'·g - f·g') / g²",
      "(f·g' - f'·g) / g²",
    ],
    answer: 2,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Uma função f é contínua em x = a quando:',
    options: [
      'f(a) existe, ainda que o limite não exista',
      'o limite de f em a existe e é igual a f(a)',
      'a derivada de f em a existe',
      'apenas o limite lateral à direita existe',
    ],
    answer: 1,
  },

  // Estatística — entrou em Matemática quando o tema passou a cobri-la.
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a média aritmética de 2, 4, 6 e 8?',
    options: ['4', '5', '6', '20'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'O que é a mediana de um conjunto de valores?',
    options: [
      'O valor que mais se repete',
      'A soma dividida pela quantidade',
      'O valor central com os dados ordenados',
      'A diferença entre o maior e o menor',
    ],
    answer: 2,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a moda do conjunto 3, 3, 5, 7?',
    options: ['3', '4,5', '5', '7'],
    answer: 0,
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a probabilidade de sair cara ao lançar uma moeda honesta?',
    options: ['1/4', '1/3', '1/2', '2/3'],
    answer: 2,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'O que o desvio padrão mede?',
    options: [
      'Quanto os valores se afastam da média',
      'O valor central da amostra',
      'A soma de todos os valores',
      'O total de elementos observados',
    ],
    answer: 0,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Qual é a diferença entre amostra e população?',
    options: [
      'População é sempre formada por pessoas',
      'A amostra é um subconjunto da população',
      'Amostra e população são sinônimos em estatística',
      'A amostra é sempre maior que a população',
    ],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Qual é a mediana do conjunto 1, 3, 4 e 10?',
    options: ['3', '3,5', '4', '4,5'],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt:
      'Numa distribuição normal, cerca de 68% dos dados estão a que distância da média?',
    options: [
      'Meio desvio padrão',
      'Um desvio padrão',
      'Dois desvios padrão',
      'Três desvios padrão',
    ],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt:
      'Duas variáveis têm correlação alta. O que NÃO se pode concluir daí?',
    options: [
      'Que elas variam juntas nos dados observados',
      'Que uma causa a outra',
      'Que existe associação estatística entre elas',
      'Que o coeficiente de correlação está longe de zero',
    ],
    answer: 1,
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'O que caracteriza uma amostragem aleatória simples?',
    options: [
      'Escolher os primeiros elementos da lista',
      'Dividir a população em grupos e sortear grupos inteiros',
      'Todo elemento da população tem a mesma chance de ser sorteado',
      'Selecionar quem se voluntaria a participar',
    ],
    answer: 2,
  },

  // ── IA ────────────────────────────────────────────────────────────────────────
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Aprendizado supervisionado precisa de dados:',
    options: [
      'Rotulados',
      'Sem rótulo nenhum',
      'Sempre numéricos',
      'Gerados aleatoriamente',
    ],
    answer: 0,
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'O que caracteriza o overfitting?',
    options: [
      'O modelo vai mal no treino e no teste',
      'O modelo vai muito bem no treino e mal em dados novos',
      'O modelo treina rápido demais',
      'O modelo usa poucos dados de teste',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'O algoritmo K-means pertence a qual categoria?',
    options: [
      'Aprendizado supervisionado',
      'Aprendizado não supervisionado',
      'Aprendizado por reforço',
      'Busca heurística',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Qual destes é um problema de classificação?',
    options: [
      'Prever o preço de um imóvel',
      'Prever se um e-mail é spam ou não',
      'Agrupar clientes parecidos',
      'Reduzir a dimensão dos dados',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'Para que serve separar os dados em treino e teste?',
    options: [
      'Para o treino ficar mais rápido',
      'Para estimar o desempenho em dados nunca vistos',
      'Para equilibrar as classes',
      'Para evitar dados faltantes',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt:
      'Qual função de ativação é usada na saída para gerar uma probabilidade em classificação binária?',
    options: ['ReLU', 'Sigmoide', 'Tangente hiperbólica', 'Linear'],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'Na matriz de confusão, um falso positivo é quando o modelo:',
    options: [
      'Previu positivo e o caso era negativo',
      'Previu negativo e o caso era positivo',
      'Acertou um caso positivo',
      'Acertou um caso negativo',
    ],
    answer: 0,
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt:
      'Em uma base muito desbalanceada, qual métrica é mais informativa que a acurácia?',
    options: [
      'F1-score',
      'Erro quadrático médio',
      'Número de épocas',
      'Perplexidade',
    ],
    answer: 0,
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'O que o backpropagation faz em uma rede neural?',
    options: [
      'Inicializa os pesos aleatoriamente',
      'Propaga o gradiente do erro para ajustar os pesos',
      'Normaliza os dados de entrada',
      'Escolhe a arquitetura da rede',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'Para que serve a regularização L2 (ridge)?',
    options: [
      'Aumentar a capacidade do modelo',
      'Penalizar pesos grandes e reduzir o overfitting',
      'Acelerar a convergência do gradiente',
      'Balancear as classes do conjunto',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'O que caracteriza o underfitting?',
    options: [
      'O modelo decora o conjunto de treino',
      'O modelo é simples demais e erra até no treino',
      'O modelo dispensa dados rotulados',
      'O modelo tem acurácia perfeita',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'O que é uma feature em aprendizado de máquina?',
    options: [
      'Um atributo de entrada usado pelo modelo',
      'O valor que o modelo prevê',
      'O erro cometido pelo modelo',
      'O número de camadas da rede',
    ],
    answer: 0,
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Qual destes é um problema de regressão?',
    options: [
      'Dizer se um e-mail é spam',
      'Classificar fotos em cão ou gato',
      'Prever o preço de um imóvel',
      'Agrupar clientes parecidos',
    ],
    answer: 2,
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Um conjunto de dados rotulado é exigido por qual abordagem?',
    options: [
      'Aprendizado supervisionado',
      'Aprendizado não supervisionado',
      'Agrupamento',
      'Redução de dimensionalidade',
    ],
    answer: 0,
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'O que a acurácia de um classificador mede?',
    options: [
      'A proporção de previsões corretas sobre o total',
      'Apenas os acertos da classe positiva',
      'O erro médio quadrático',
      'O tempo gasto no treino',
    ],
    answer: 0,
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'O que a validação cruzada (cross-validation) estima?',
    options: [
      'O tamanho ideal do conjunto de dados',
      'O desempenho do modelo usando várias divisões dos dados',
      'O número mínimo de atributos necessários',
      'O rótulo correto de cada exemplo não rotulado',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'O que é a taxa de aprendizado (learning rate)?',
    options: [
      'A porcentagem de dados separada para treino',
      'A acurácia mínima aceita',
      'O tamanho do passo na atualização dos pesos',
      'O número de épocas de treino',
    ],
    answer: 2,
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'Na matriz de confusão, o que o recall (revocação) mede?',
    options: [
      'A fração dos positivos reais que o modelo encontrou',
      'A fração das previsões positivas que estavam certas',
      'O total de acertos sobre o total de exemplos',
      'O erro absoluto médio',
    ],
    answer: 0,
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'Para que serve a função de ativação em uma rede neural?',
    options: [
      'Normalizar os dados de entrada',
      'Introduzir não linearidade entre as camadas',
      'Reduzir o número de neurônios',
      'Calcular o gradiente automaticamente',
    ],
    answer: 1,
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'O que o gradiente descendente faz durante o treino?',
    options: [
      'Sorteia os pesos iniciais da rede',
      'Ajusta os pesos na direção que reduz a função de perda',
      'Aumenta a função de perda para explorar o espaço',
      'Remove os atributos irrelevantes',
    ],
    answer: 1,
  },

  // ── Robótica ──────────────────────────────────────────────────────────────────
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Qual componente converte sinal elétrico em movimento?',
    options: ['Sensor', 'Atuador', 'Resistor', 'Barramento'],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Um sensor ultrassônico mede principalmente:',
    options: ['Temperatura', 'Distância', 'Luminosidade', 'Corrente elétrica'],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Para que serve um encoder acoplado a um motor?',
    options: [
      'Aumentar o torque',
      'Medir rotação e posição do eixo',
      'Filtrar ruído elétrico',
      'Converter tensão em corrente',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'O que um servo motor controla diretamente?',
    options: [
      'A posição angular',
      'A temperatura do circuito',
      'A tensão da fonte',
      'A frequência do clock',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Em um controlador PID, o termo integral (I) corrige:',
    options: [
      'O erro instantâneo',
      'O erro acumulado ao longo do tempo',
      'A velocidade de variação do erro',
      'O ruído do sensor',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Para que serve o PWM no controle de motores?',
    options: [
      'Inverter o sentido de rotação',
      'Controlar a potência média variando a largura do pulso',
      'Medir a corrente do motor',
      'Converter sinal analógico em digital',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'O que são os graus de liberdade de um braço robótico?',
    options: [
      'O número de motores instalados',
      'O número de movimentos independentes possíveis',
      'O alcance máximo em metros',
      'A carga máxima suportada',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O que a cinemática inversa calcula?',
    options: [
      'A posição da garra a partir dos ângulos das juntas',
      'Os ângulos das juntas a partir da posição desejada da garra',
      'A força necessária em cada junta',
      'A trajetória de menor consumo de energia',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt:
      'Qual barramento é o padrão de comunicação entre módulos em veículos e automação industrial?',
    options: ['CAN', 'HDMI', 'SATA', 'VGA'],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O termo derivativo (D) de um PID reage a quê?',
    options: [
      'Ao valor absoluto do erro',
      'À taxa de variação do erro, amortecendo oscilações',
      'À soma histórica do erro',
      'Ao valor de referência',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'O que um atuador faz em um robô?',
    options: [
      'Converte um comando em ação física',
      'Mede grandezas do ambiente',
      'Armazena o programa em execução',
      'Comunica o robô com a rede',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Para que serve um motor de passo?',
    options: [
      'Medir a temperatura do circuito',
      'Girar em incrementos angulares precisos',
      'Gerar energia para os sensores',
      'Amplificar o sinal do encoder',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Qual é a função do microcontrolador em um robô?',
    options: [
      'Fornecer torque ao eixo',
      'Isolar o circuito de potência',
      'Executar o programa e comandar os periféricos',
      'Medir a distância até o obstáculo',
    ],
    answer: 2,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Um sensor de proximidade indutivo detecta:',
    options: [
      'A presença de objetos metálicos sem contato',
      'A temperatura da superfície',
      'A cor do objeto à frente',
      'A carga restante da bateria',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Em um controlador PID, o termo proporcional (P) reage a quê?',
    options: [
      'Ao erro atual',
      'Ao acúmulo do erro ao longo do tempo',
      'À velocidade de variação do erro',
      'Apenas ao valor desejado',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'O que é odometria em um robô móvel?',
    options: [
      'Detectar obstáculos por ultrassom',
      'Planejar a trajetória de menor custo',
      'Estimar a posição a partir do movimento das rodas',
      'Controlar a corrente do motor',
    ],
    answer: 2,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Para que serve uma ponte H no acionamento de um motor?',
    options: [
      'Inverter o sentido de rotação',
      'Medir a corrente consumida',
      'Converter sinal analógico em digital',
      'Alimentar os sensores em 3,3 V',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O que a cinemática direta calcula?',
    options: [
      'Os ângulos das juntas a partir da posição desejada',
      'A posição do efetuador a partir dos ângulos das juntas',
      'A força necessária em cada junta',
      'O tempo de resposta do controlador',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'Por que um controle em malha fechada usa realimentação?',
    options: [
      'Para corrigir o comando a partir do erro medido',
      'Para dispensar o uso de sensores',
      'Para reduzir o consumo do motor',
      'Para acelerar o processamento do microcontrolador',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O que é o espaço de configuração de um robô?',
    options: [
      'A área física ocupada pela base',
      'A memória disponível no controlador',
      'O conjunto de todas as posições possíveis das juntas',
      'A faixa de tensão de operação',
    ],
    answer: 2,
  },

  // ── Arquitetura ───────────────────────────────────────────────────────────────
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual unidade da CPU executa as operações aritméticas e lógicas?',
    options: ['ULA', 'Cache', 'Barramento', 'Controlador de memória'],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual é a memória mais rápida e mais próxima do núcleo da CPU?',
    options: ['Registradores', 'Cache L3', 'Memória RAM', 'SSD'],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Quantos bits tem 1 byte?',
    options: ['4', '8', '16', '32'],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'A memória RAM é classificada como:',
    options: [
      'Volátil (perde o conteúdo sem energia)',
      'Não volátil',
      'Somente leitura',
      'Memória secundária',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Para que serve o pipeline de instruções?',
    options: [
      'Reduzir o consumo de energia',
      'Sobrepor as etapas de várias instruções e aumentar a vazão',
      'Aumentar o tamanho da cache',
      'Executar instruções fora de ordem',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que caracteriza uma arquitetura RISC frente a uma CISC?',
    options: [
      'Instruções mais numerosas e complexas',
      'Conjunto de instruções reduzido e regular',
      'Ausência de registradores',
      'Execução exclusivamente sequencial',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que significa um cache miss?',
    options: [
      'A cache foi corrompida',
      'O dado não estava na cache e precisou ser buscado na memória',
      'A cache está desativada',
      'A instrução foi descartada',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Quando ocorre um hazard de dados no pipeline?',
    options: [
      'Quando duas instruções usam a mesma unidade funcional',
      'Quando uma instrução depende de um resultado ainda não disponível',
      'Quando um desvio é previsto incorretamente',
      'Quando a memória está cheia',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'O princípio da localidade temporal diz que:',
    options: [
      'Endereços vizinhos tendem a ser acessados juntos',
      'Um dado acessado tende a ser acessado de novo em breve',
      'Instruções são executadas em ordem',
      'A cache deve ser esvaziada periodicamente',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'A Lei de Amdahl mostra que o ganho ao paralelizar é limitado:',
    options: [
      'Pela quantidade de memória disponível',
      'Pela fração do programa que continua sequencial',
      'Pela frequência do processador',
      'Pelo número de instruções do programa',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Quantos bytes tem 1 kibibyte (KiB)?',
    options: ['512', '1000', '1024', '2048'],
    answer: 2,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual registrador guarda o endereço da próxima instrução?',
    options: [
      'O contador de programa (PC)',
      'A unidade lógica e aritmética',
      'O cache L2',
      'O barramento de dados',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'A memória ROM caracteriza-se por:',
    options: [
      'Ser mais rápida que o cache L1',
      'Não perder o conteúdo ao desligar o computador',
      'Ser volátil como a RAM',
      'Existir apenas em servidores',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'O que trafega pelo barramento de dados?',
    options: [
      'Apenas endereços de memória',
      'Apenas sinais de controle',
      'Os valores lidos e escritos na memória',
      'A energia vinda da fonte',
    ],
    answer: 2,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que caracteriza a arquitetura de von Neumann?',
    options: [
      'Dados e instruções compartilham a mesma memória',
      'Dados e instruções ficam em memórias fisicamente separadas',
      'Não existe unidade de controle',
      'O processador é obrigatoriamente multinúcleo',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Quando ocorre um cache hit?',
    options: [
      'Quando o dado precisa ser buscado na memória principal',
      'Quando o dado procurado já está no cache',
      'Quando o pipeline é esvaziado',
      'Quando há erro de paridade na memória',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que a memória virtual oferece a cada processo?',
    options: [
      'Uma frequência de operação maior no processador',
      'Um substituto para o cache L1 em sistemas antigos',
      'Um espaço de endereços maior que a RAM física disponível',
      'Um barramento de endereços dedicado',
    ],
    answer: 2,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'O princípio da localidade espacial diz que:',
    options: [
      'Endereços vizinhos ao acessado tendem a ser acessados em seguida',
      'O mesmo endereço tende a ser acessado de novo em breve',
      'O cache precisa ser maior que a memória principal',
      'As instruções são sempre executadas fora de ordem',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Um hazard de controle no pipeline é causado por:',
    options: [
      'Duas instruções que disputam o mesmo registrador',
      'Desvios condicionais cujo destino ainda não é conhecido',
      'Falta de energia no barramento',
      'Um cache totalmente associativo',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Para que serve a previsão de desvio (branch prediction)?',
    options: [
      'Reduzir o consumo de energia da ULA',
      'Aumentar o tamanho efetivo do cache',
      'Ordenar os acessos à memória principal',
      'Evitar bolhas no pipeline antecipando o caminho do desvio',
    ],
    answer: 3,
  },

  // ── Engenharia de Software ────────────────────────────────────────────────────
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'O que é um requisito funcional?',
    options: [
      'O que o sistema deve fazer',
      'O prazo de entrega do projeto',
      'A linguagem escolhida para programar',
      'O orçamento aprovado pelo cliente',
    ],
    answer: 0,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'Num diagrama de casos de uso, o que é um ator?',
    options: [
      'Uma tabela do banco de dados',
      'Quem interage com o sistema, seja pessoa ou outro sistema',
      'Uma tela da interface',
      'Um método de uma classe',
    ],
    answer: 1,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt:
      'Qual diagrama da UML mostra classes, seus atributos e os relacionamentos entre elas?',
    options: [
      'Diagrama de sequência',
      'Diagrama de atividades',
      'Diagrama de classes',
      'Diagrama de implantação',
    ],
    answer: 2,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'O que um teste unitário verifica?',
    options: [
      'O sistema inteiro rodando em produção',
      'A experiência do usuário na interface',
      'A comunicação com serviços externos',
      'Uma unidade isolada de código',
    ],
    answer: 3,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'No Scrum, o que é a reunião diária (daily)?',
    options: [
      'Um encontro curto de alinhamento do time',
      'A apresentação do incremento ao cliente',
      'A reunião de planejamento da sprint',
      'A retrospectiva do ciclo anterior',
    ],
    answer: 0,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'Para que serve um sistema de controle de versão como o Git?',
    options: [
      'Hospedar o site em produção',
      'Registrar o histórico de alterações do código',
      'Compilar o projeto mais rápido',
      'Medir o desempenho da aplicação',
    ],
    answer: 1,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'O que é um bug em engenharia de software?',
    options: [
      'Qualquer mensagem exibida ao usuário',
      'Um recurso ainda não implementado',
      'Um comportamento diferente do que foi especificado',
      'Uma linha de código muito longa',
    ],
    answer: 2,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'O que o backlog do produto guarda?',
    options: [
      'Os defeitos já corrigidos',
      'O histórico de reuniões do time',
      'Os contratos assinados com o cliente',
      'A lista priorizada do que ainda falta fazer',
    ],
    answer: 3,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'Qual destes é um requisito NÃO funcional?',
    options: [
      'O sistema deve emitir nota fiscal',
      'O sistema deve responder em até 2 segundos',
      'O sistema deve cadastrar clientes',
      'O sistema deve permitir login',
    ],
    answer: 1,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'Em BPMN, o que um losango (gateway) representa no fluxo?',
    options: [
      'O início do processo',
      'Uma tarefa executada por pessoa',
      'Um ponto de decisão ou desvio',
      'O envio de uma mensagem',
    ],
    answer: 2,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'Qual é a diferença entre verificação e validação?',
    options: [
      'Verificação é automática; validação é sempre manual',
      'Verificação ocorre depois da entrega; validação, antes',
      'Verificação checa se construímos certo; validação, se é o produto certo',
      'São nomes diferentes para a mesma atividade',
    ],
    answer: 2,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'O que caracteriza o modelo cascata em relação aos iterativos?',
    options: [
      'As fases são sequenciais e voltar atrás sai caro',
      'Cada ciclo entrega uma parte utilizável do produto',
      'Os requisitos podem mudar a cada semana sem custo',
      'Não existe fase de testes',
    ],
    answer: 0,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt:
      'Num diagrama de classes, o que a multiplicidade 1..* indica numa associação?',
    options: [
      'Nenhuma ou uma instância associada',
      'Exatamente uma instância associada',
      'No máximo uma instância associada',
      'Pelo menos uma instância associada',
    ],
    answer: 3,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'O que é dívida técnica?',
    options: [
      'O valor que o cliente ainda deve pagar pelo projeto',
      'O custo futuro de uma solução rápida adotada hoje',
      'A quantidade de bugs abertos no sistema',
      'O tempo gasto em reuniões durante a sprint',
    ],
    answer: 1,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'Qual é a diferença entre agregação e composição na UML?',
    options: [
      'Agregação só vale entre classes abstratas',
      'Composição é representada por uma seta tracejada',
      'Na composição, a parte não existe sem o todo',
      'Agregação implica herança entre as classes',
    ],
    answer: 2,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'Para que serve um teste de regressão?',
    options: [
      'Medir o tempo de resposta sob carga',
      'Garantir que uma mudança não quebrou o que já funcionava',
      'Validar a usabilidade com usuários reais',
      'Verificar a cobertura de código do projeto',
    ],
    answer: 1,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'O que a rastreabilidade de requisitos permite?',
    options: [
      'Ligar cada requisito aos artefatos que o implementam e testam',
      'Descobrir quem escreveu cada linha de código',
      'Medir a produtividade individual do time',
      'Estimar o custo de hospedagem do sistema',
    ],
    answer: 0,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'O que um diagrama de sequência da UML representa?',
    options: [
      'A estrutura estática das classes do sistema',
      'A distribuição dos componentes nos servidores',
      'A troca de mensagens entre objetos ao longo do tempo',
      'A ordem de prioridade dos requisitos',
    ],
    answer: 2,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'Em BPMN, para que serve uma raia (lane) dentro de uma piscina?',
    options: [
      'Marcar o fim do processo',
      'Indicar um subprocesso reutilizável',
      'Registrar o tempo de cada atividade',
      'Separar responsabilidades dentro do mesmo processo',
    ],
    answer: 3,
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'O que é a "definição de pronto" (Definition of Done) de um time?',
    options: [
      'O prazo combinado para a entrega final',
      'O critério comum que diz quando um item está realmente concluído',
      'A lista de requisitos aprovada pelo cliente',
      'O número de pontos entregues na sprint',
    ],
    answer: 1,
  },

  // ── Redes ─────────────────────────────────────────────────────────────────────
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual protocolo traduz nomes de domínio em endereços IP?',
    options: ['DHCP', 'DNS', 'FTP', 'SMTP'],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual é a porta padrão do HTTPS?',
    options: ['21', '80', '443', '8080'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'O protocolo TCP é:',
    options: [
      'Orientado a conexão e confiável',
      'Sem conexão e sem garantias',
      'Exclusivo de redes sem fio',
      'Usado apenas para streaming',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'O que é um endereço IP?',
    options: [
      'O identificador do dispositivo na rede',
      'O número de série do equipamento',
      'A senha de acesso ao roteador',
      'O nome do domínio do site',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Qual é a principal diferença do UDP para o TCP?',
    options: [
      'O UDP é mais lento',
      'O UDP não garante entrega nem ordem dos pacotes',
      'O UDP só funciona em rede local',
      'O UDP criptografa os dados',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Em qual camada do modelo OSI atua um roteador?',
    options: ['Física (1)', 'Enlace (2)', 'Rede (3)', 'Transporte (4)'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'O que o NAT faz?',
    options: [
      'Criptografa o tráfego de saída',
      'Traduz endereços privados em um endereço público',
      'Distribui endereços IP na rede local',
      'Resolve nomes de domínio',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Qual é a sequência do three-way handshake do TCP?',
    options: [
      'SYN, ACK, FIN',
      'SYN, SYN-ACK, ACK',
      'ACK, SYN, ACK',
      'SYN, FIN, ACK',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Quantos endereços de host utilizáveis tem uma sub-rede /24?',
    options: ['128', '254', '255', '256'],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Para que serve o campo TTL de um pacote IP?',
    options: [
      'Definir a prioridade do pacote',
      'Impedir que pacotes circulem indefinidamente em loops',
      'Indicar o tamanho do pacote',
      'Identificar o protocolo de transporte',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual é a porta padrão do HTTP?',
    options: ['21', '25', '80', '443'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'O que um servidor DHCP faz?',
    options: [
      'Distribui endereços IP automaticamente na rede',
      'Traduz nomes de domínio em endereços',
      'Filtra pacotes maliciosos',
      'Criptografa todo o tráfego da rede',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'A que corresponde o endereço 127.0.0.1?',
    options: [
      'Ao gateway padrão da rede',
      'Ao próprio host (loopback)',
      'Ao servidor DNS público',
      'Ao endereço de broadcast',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual dispositivo interliga redes diferentes?',
    options: ['O repetidor', 'O switch', 'O roteador', 'O hub'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Em qual camada do modelo OSI atua um switch?',
    options: [
      'Camada 1 (física)',
      'Camada 2 (enlace)',
      'Camada 3 (rede)',
      'Camada 4 (transporte)',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'O que o protocolo ARP resolve?',
    options: [
      'O endereço MAC correspondente a um endereço IP',
      'O nome de domínio correspondente a um IP',
      'A melhor rota até o destino',
      'A porta usada por um serviço',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Para que serve uma VLAN?',
    options: [
      'Aumentar a velocidade nominal do cabo',
      'Criptografar o tráfego dentro do switch',
      'Separar logicamente redes que compartilham o mesmo switch',
      'Substituir o roteador de borda',
    ],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Quantos endereços de host utilizáveis tem uma sub-rede /26?',
    options: ['30', '62', '64', '126'],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'O que o TLS acrescenta ao HTTP?',
    options: [
      'Compressão dos dados transmitidos',
      'Roteamento entre redes distintas',
      'Confidencialidade e autenticação do servidor',
      'Controle de congestionamento',
    ],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Para que serve o controle de congestionamento do TCP?',
    options: [
      'Ajustar a taxa de envio ao que a rede suporta',
      'Garantir a ordem de entrega dos pacotes',
      'Traduzir endereços privados em públicos',
      'Descobrir a rota mais curta até o destino',
    ],
    answer: 0,
  },

  // ── Banco de Dados ────────────────────────────────────────────────────────────
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando SQL é usado para consultar dados?',
    options: ['INSERT', 'SELECT', 'UPDATE', 'CREATE'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Para que serve uma chave primária?',
    options: [
      'Identificar unicamente cada linha da tabela',
      'Ordenar os resultados da consulta',
      'Ligar o banco à aplicação',
      'Criptografar a coluna',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando remove linhas de uma tabela?',
    options: ['DROP', 'DELETE', 'REMOVE', 'TRUNCATE COLUMN'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Em um banco relacional, uma tabela é composta por:',
    options: [
      'Linhas e colunas',
      'Documentos e coleções',
      'Chaves e valores',
      'Nós e arestas',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'O que um INNER JOIN retorna?',
    options: [
      'Todas as linhas das duas tabelas',
      'Apenas as linhas com correspondência nas duas tabelas',
      'Todas as linhas da tabela da esquerda',
      'As linhas sem correspondência',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Para que serve um índice em uma tabela?',
    options: [
      'Reduzir o espaço ocupado pelos dados',
      'Acelerar as buscas, ao custo de escrita e espaço',
      'Garantir que os dados não se repitam',
      'Fazer backup automático das linhas',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'O que uma chave estrangeira garante?',
    options: [
      'A ordenação das linhas',
      'A integridade referencial entre tabelas',
      'A unicidade da coluna',
      'A criptografia do relacionamento',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Nas propriedades ACID, o que significa o "I"?',
    options: ['Integridade', 'Isolamento', 'Indexação', 'Imutabilidade'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'O que um LEFT JOIN retorna?',
    options: [
      'Só as linhas com correspondência',
      'Todas as linhas da tabela da esquerda, com NULL onde não há par',
      'Todas as linhas das duas tabelas',
      'As linhas duplicadas da direita',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'A terceira forma normal (3FN) elimina:',
    options: [
      'Grupos repetitivos',
      'Dependências parciais da chave',
      'Dependências transitivas entre atributos não-chave',
      'Chaves estrangeiras redundantes',
    ],
    answer: 2,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando SQL insere novas linhas em uma tabela?',
    options: ['INSERT', 'SELECT', 'UPDATE', 'DROP'],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando SQL altera dados já existentes?',
    options: ['SELECT', 'UPDATE', 'INSERT', 'CREATE'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'O que a cláusula WHERE faz em um SELECT?',
    options: [
      'Ordena o resultado',
      'Agrupa as linhas por um campo',
      'Filtra quais linhas entram no resultado',
      'Junta duas tabelas',
    ],
    answer: 2,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Em SQL, o que o valor NULL representa?',
    options: [
      'Ausência de valor',
      'O número zero',
      'Uma string vazia',
      'O valor booleano falso',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Para que serve a cláusula GROUP BY?',
    options: [
      'Ordenar o resultado da consulta',
      'Agrupar linhas para aplicar funções de agregação',
      'Remover linhas duplicadas do filtro',
      'Criar um índice na tabela',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'O que a cláusula ORDER BY faz?',
    options: [
      'Filtra as linhas do resultado',
      'Agrupa as linhas por um campo',
      'Ordena as linhas do resultado',
      'Limita a quantidade de linhas retornadas',
    ],
    answer: 2,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Qual é a diferença entre DELETE e TRUNCATE?',
    options: [
      'DELETE remove linhas com filtro; TRUNCATE esvazia a tabela inteira',
      'TRUNCATE aceita WHERE e DELETE não',
      'DELETE apaga a tabela; TRUNCATE apaga o banco',
      'Não há diferença entre os dois',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Nas propriedades ACID, o que significa o "A"?',
    options: [
      'Acessibilidade dos dados a qualquer usuário',
      'Auditoria de todas as operações',
      'Alta disponibilidade do servidor',
      'Atomicidade: a transação vale por inteiro ou não vale',
    ],
    answer: 3,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'O que a segunda forma normal (2FN) exige?',
    options: [
      'Que todo atributo não chave dependa da chave primária inteira',
      'Que nenhuma coluna aceite valores nulos',
      'Que exista um índice em cada coluna',
      'Que a tabela tenha no máximo dez colunas',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Por que um índice pode deixar a escrita mais lenta?',
    options: [
      'Porque bloqueia a tabela inteira a cada consulta',
      'Porque cada gravação precisa atualizar também a estrutura do índice',
      'Porque duplica todas as linhas da tabela',
      'Porque desativa o cache do banco',
    ],
    answer: 1,
  },

  // ── Algoritmos ────────────────────────────────────────────────────────────────
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é a complexidade da busca binária?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Qual estrutura de dados segue a regra "último a entrar, primeiro a sair"?',
    options: ['Fila', 'Pilha', 'Lista ligada', 'Árvore'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Qual estrutura de dados segue a regra "primeiro a entrar, primeiro a sair"?',
    options: ['Pilha', 'Fila', 'Grafo', 'Tabela hash'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Na busca linear em uma lista de n elementos, quantas comparações o pior caso exige?',
    options: ['1', 'log n', 'n', 'n²'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a complexidade do quicksort no caso médio?',
    options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'O que toda função recursiva precisa ter para terminar?',
    options: [
      'Um caso base',
      'Um laço de repetição',
      'Uma variável global',
      'Um vetor auxiliar',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é o pré-requisito para aplicar busca binária?',
    options: [
      'A lista precisa estar ordenada',
      'A lista precisa ter tamanho par',
      'Os elementos precisam ser numéricos',
      'A lista precisa caber na memória cache',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Qual é a complexidade do quicksort no pior caso?',
    options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'O que a programação dinâmica evita?',
    options: [
      'O uso de recursão',
      'O recálculo de subproblemas que já foram resolvidos',
      'A alocação de memória extra',
      'O uso de estruturas ordenadas',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Qual é a complexidade média de inserção em uma tabela hash?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Qual é a complexidade de acessar um elemento de um vetor pelo índice?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'O que cada nó de uma lista encadeada guarda?',
    options: [
      'Apenas o valor armazenado',
      'O valor e a referência para o próximo nó',
      'O índice e o tamanho da lista',
      'Uma cópia do vetor inteiro',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é a complexidade do bubble sort no pior caso?',
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(n²)'],
    answer: 3,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'O que um algoritmo de ordenação faz?',
    options: [
      'Organiza os elementos segundo um critério',
      'Remove os elementos repetidos',
      'Localiza um elemento específico',
      'Conta quantos elementos existem',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a complexidade do merge sort em qualquer caso?',
    options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Em uma árvore binária de busca equilibrada, quanto custa a busca?',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Como um algoritmo guloso (greedy) toma cada decisão?',
    options: [
      'Escolhe o melhor local a cada passo, sem revisar a decisão',
      'Testa todas as combinações possíveis',
      'Divide o problema ao meio a cada chamada',
      'Guarda a solução de cada subproblema resolvido',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt:
      'Qual é a complexidade de inserir no início de uma lista encadeada?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'O que a notação O(f(n)) descreve?',
    options: [
      'O tempo exato de execução em segundos',
      'Um limite superior para o crescimento do custo',
      'O consumo de memória, e apenas ele',
      'O número de linhas do código-fonte',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt:
      'Qual é a diferença entre busca em largura (BFS) e em profundidade (DFS)?',
    options: [
      'BFS usa pilha e DFS usa fila',
      'BFS só funciona em árvores; DFS, em grafos',
      'BFS explora por níveis; DFS desce por um ramo até o fim',
      'DFS sempre encontra o caminho mais curto',
    ],
    answer: 2,
  },

  // Vindas do tema Lógica, que saiu da roda: dedução, tabela-verdade e
  // raciocínio formal passaram a contar como Algoritmos. O tema fica com o
  // dobro das outras — pool maior não muda nada para o aluno, que sorteia uma
  // questão por vez.
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é a negação de "todo aluno foi aprovado"?',
    options: [
      'Nenhum aluno foi aprovado',
      'Pelo menos um aluno não foi aprovado',
      'Todo aluno foi reprovado',
      'Alguns alunos foram aprovados',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é o valor de "verdadeiro E falso"?',
    options: ['Verdadeiro', 'Falso', 'Indefinido', 'Depende da ordem'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      '"Se chove, a rua fica molhada." Sabendo que está chovendo, o que se conclui?',
    options: [
      'A rua fica molhada',
      'A rua está seca',
      'Nada se conclui',
      'Não está chovendo',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Com p falso e q verdadeiro, qual é o valor de "p OU q"?',
    options: ['Falso', 'Verdadeiro', 'Indefinido', 'Igual ao de p E q'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a contrapositiva de "se p, então q"?',
    options: [
      'Se q, então p',
      'Se não p, então não q',
      'Se não q, então não p',
      'p e não q',
    ],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Quantas linhas tem a tabela-verdade de 4 proposições simples?',
    options: ['8', '12', '16', '32'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'A proposição "p → q" é equivalente a qual expressão?',
    options: ['p E q', 'não p OU q', 'p OU não q', 'não p E q'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Pela lei de De Morgan, "não (p E q)" equivale a:',
    options: ['não p E não q', 'não p OU não q', 'p OU q', 'não (p OU q)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt:
      'Concluir p a partir de "se p, então q" e de q é qual erro de raciocínio?',
    options: [
      'Afirmação do consequente',
      'Negação do antecedente',
      'Modus tollens',
      'Silogismo hipotético',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Qual das proposições abaixo é uma tautologia?',
    options: ['p E não p', 'p OU não p', 'p → não p', 'não (p OU p)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é o valor de "falso OU falso"?',
    options: ['Verdadeiro', 'Falso', 'Indefinido', 'Depende da ordem'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é a negação de "nenhum aluno faltou"?',
    options: [
      'Todo aluno faltou',
      'Nenhum aluno compareceu',
      'Pelo menos um aluno faltou',
      'Todos compareceram',
    ],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Quantas linhas tem a tabela-verdade de 2 proposições simples?',
    options: ['2', '4', '6', '8'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'O conectivo "E" (conjunção) só é verdadeiro quando:',
    options: [
      'Pelo menos uma das partes é verdadeira',
      'As duas partes são verdadeiras',
      'As duas partes são falsas',
      'Uma das partes é falsa',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a recíproca de "se p, então q"?',
    options: [
      'Se não q, então não p',
      'Se não p, então não q',
      'Se q, então p',
      'p e não q',
    ],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt:
      'Em quantas linhas da tabela-verdade a proposição "p OU q" é falsa?',
    options: ['Nenhuma', 'Uma', 'Duas', 'Três'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Pela lei de De Morgan, "não (p OU q)" equivale a:',
    options: [
      '(não p) OU (não q)',
      '(não p) E (não q)',
      'p E q',
      'p OU (não q)',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt:
      'Como se chama a proposição que é falsa em todas as linhas da tabela-verdade?',
    options: ['Tautologia', 'Contingência', 'Contradição', 'Bicondicional'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'A bicondicional "p ↔ q" é verdadeira exatamente quando:',
    options: [
      'p e q têm o mesmo valor lógico',
      'p é verdadeira e q é falsa',
      'Pelo menos uma das duas é verdadeira',
      'As duas são falsas',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt:
      'Pelo modus tollens, de "se p, então q" e "não q" o que se conclui?',
    options: ['q', 'p', 'não p', 'Nada se conclui'],
    answer: 2,
  },
];
