/**
 * Banco de questões do quiz de bancada — 20 por tema da roda de tipos.
 *
 * Fonte para o seed (`npm run db:seed-quiz`); em runtime o servidor lê da
 * tabela `quiz_questions`, nunca deste arquivo. O enunciado é a chave: mudar o
 * texto cria uma questão nova, mudar as alternativas atualiza a existente.
 *
 * Cada tema tem 8 fáceis, 6 médias e 6 difíceis — a proporção 4:3:3 que o
 * sorteio usa como peso (ver `QUIZ_DIFFICULTY_MIX`). O tamanho não é estético:
 * o aluno nunca recebe uma questão que já respondeu no tema enquanto houver
 * inédita, e com 10 por tema quem passava o dia no estande esgotava o banco
 * antes do fim do evento.
 *
 * A ordem das alternativas aqui é só a de cadastro — o servidor embaralha a
 * cada aplicação, senão a fila da bancada decoraria a posição da resposta.
 */

export type QuizDifficulty = 'facil' | 'media' | 'dificil';

export interface QuizSeedQuestion {
  theme: string;
  difficulty: QuizDifficulty;
  prompt: string;
  options: string[];
  /** Índice da alternativa correta em `options`. */
  answer: number;
}

export const QUIZ_QUESTIONS: QuizSeedQuestion[] = [
  // ── Lógica ────────────────────────────────────────────────────────────────
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt: 'Qual é a negação de "todo aluno foi aprovado"?',
    options: [
      'Nenhum aluno foi aprovado',
      'Pelo menos um aluno não foi aprovado',
      'Todo aluno foi reprovado',
      'Alguns alunos foram aprovados',
    ],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt: 'Qual é o valor de "verdadeiro E falso"?',
    options: ['Verdadeiro', 'Falso', 'Indefinido', 'Depende da ordem'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt:
      '"Se chove, a rua fica molhada." Sabendo que está chovendo, o que se conclui?',
    options: [
      'A rua fica molhada',
      'A rua está seca',
      'Nada se conclui',
      'Não está chovendo',
    ],
    answer: 0,
  },
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt: 'Com p falso e q verdadeiro, qual é o valor de "p OU q"?',
    options: ['Falso', 'Verdadeiro', 'Indefinido', 'Igual ao de p E q'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'media',
    prompt: 'Qual é a contrapositiva de "se p, então q"?',
    options: [
      'Se q, então p',
      'Se não p, então não q',
      'Se não q, então não p',
      'p e não q',
    ],
    answer: 2,
  },
  {
    theme: 'logica',
    difficulty: 'media',
    prompt: 'Quantas linhas tem a tabela-verdade de 4 proposições simples?',
    options: ['8', '12', '16', '32'],
    answer: 2,
  },
  {
    theme: 'logica',
    difficulty: 'media',
    prompt: 'A proposição "p → q" é equivalente a qual expressão?',
    options: ['p E q', 'não p OU q', 'p OU não q', 'não p E q'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'dificil',
    prompt: 'Pela lei de De Morgan, "não (p E q)" equivale a:',
    options: ['não p E não q', 'não p OU não q', 'p OU q', 'não (p OU q)'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'dificil',
    prompt:
      'Concluir p a partir de "se p, então q" e de q é qual erro de raciocínio?',
    options: [
      'Afirmação do consequente',
      'Negação do antecedente',
      'Modus tollens',
      'Silogismo hipotético',
    ],
    answer: 0,
  },
  {
    theme: 'logica',
    difficulty: 'dificil',
    prompt: 'Qual das proposições abaixo é uma tautologia?',
    options: ['p E não p', 'p OU não p', 'p → não p', 'não (p OU p)'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt: 'Qual é o valor de "falso OU falso"?',
    options: ['Verdadeiro', 'Falso', 'Indefinido', 'Depende da ordem'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt: 'Qual é a negação de "nenhum aluno faltou"?',
    options: [
      'Todo aluno faltou',
      'Nenhum aluno compareceu',
      'Pelo menos um aluno faltou',
      'Todos compareceram',
    ],
    answer: 2,
  },
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt: 'Quantas linhas tem a tabela-verdade de 2 proposições simples?',
    options: ['2', '4', '6', '8'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'facil',
    prompt: 'O conectivo "E" (conjunção) só é verdadeiro quando:',
    options: [
      'Pelo menos uma das partes é verdadeira',
      'As duas partes são verdadeiras',
      'As duas partes são falsas',
      'Uma das partes é falsa',
    ],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'media',
    prompt: 'Qual é a recíproca de "se p, então q"?',
    options: [
      'Se não q, então não p',
      'Se não p, então não q',
      'Se q, então p',
      'p e não q',
    ],
    answer: 2,
  },
  {
    theme: 'logica',
    difficulty: 'media',
    prompt:
      'Em quantas linhas da tabela-verdade a proposição "p OU q" é falsa?',
    options: ['Nenhuma', 'Uma', 'Duas', 'Três'],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'media',
    prompt: 'Pela lei de De Morgan, "não (p OU q)" equivale a:',
    options: [
      '(não p) OU (não q)',
      '(não p) E (não q)',
      'p E q',
      'p OU (não q)',
    ],
    answer: 1,
  },
  {
    theme: 'logica',
    difficulty: 'dificil',
    prompt:
      'Como se chama a proposição que é falsa em todas as linhas da tabela-verdade?',
    options: ['Tautologia', 'Contingência', 'Contradição', 'Bicondicional'],
    answer: 2,
  },
  {
    theme: 'logica',
    difficulty: 'dificil',
    prompt: 'A bicondicional "p ↔ q" é verdadeira exatamente quando:',
    options: [
      'p e q têm o mesmo valor lógico',
      'p é verdadeira e q é falsa',
      'Pelo menos uma das duas é verdadeira',
      'As duas são falsas',
    ],
    answer: 0,
  },
  {
    theme: 'logica',
    difficulty: 'dificil',
    prompt:
      'Pelo modus tollens, de "se p, então q" e "não q" o que se conclui?',
    options: ['q', 'p', 'não p', 'Nada se conclui'],
    answer: 2,
  },

  // ── Cálculo ───────────────────────────────────────────────────────────────
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de f(x) = x²?',
    options: ['x', '2x', 'x²/2', '2'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Quanto vale o limite de (3x + 1) quando x tende a 2?',
    options: ['5', '6', '7', '9'],
    answer: 2,
  },
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de uma função constante?',
    options: ['A própria constante', '0', '1', 'x'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Qual é a integral indefinida de 2x dx?',
    options: ['x² + C', '2x² + C', 'x + C', '2 + C'],
    answer: 0,
  },
  {
    theme: 'calculo',
    difficulty: 'media',
    prompt: 'Qual é a derivada de sen(x)?',
    options: ['-sen(x)', 'cos(x)', '-cos(x)', 'tg(x)'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'media',
    prompt: 'Quanto vale o limite de sen(x)/x quando x tende a 0?',
    options: ['0', '1', 'Infinito', 'Não existe'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'media',
    prompt: 'Pela regra do produto, a derivada de f(x)·g(x) é:',
    options: [
      "f'(x)·g'(x)",
      "f'(x)·g(x) + f(x)·g'(x)",
      "f'(x)·g(x) - f(x)·g'(x)",
      "f(x)·g'(x)",
    ],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'dificil',
    prompt: 'Qual é a derivada de e^(2x)?',
    options: ['e^(2x)', '2e^(2x)', '2x·e^(2x)', 'e^(2x)/2'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'dificil',
    prompt: 'A função f(x) = x³ - 3x tem mínimo local em qual ponto?',
    options: ['x = -1', 'x = 0', 'x = 1', 'x = 3'],
    answer: 2,
  },
  {
    theme: 'calculo',
    difficulty: 'dificil',
    prompt: 'Quanto vale a integral de x² dx no intervalo de 0 a 1?',
    options: ['1/4', '1/3', '1/2', '1'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de f(x) = 5x?',
    options: ['0', '5', '5x', 'x'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Pela regra da potência, qual é a derivada de f(x) = x³?',
    options: ['3x', 'x²', '3x²', '3x³'],
    answer: 2,
  },
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Quanto vale o limite de x² quando x tende a 3?',
    options: ['3', '6', '9', 'Não existe'],
    answer: 2,
  },
  {
    theme: 'calculo',
    difficulty: 'facil',
    prompt: 'Qual é a integral indefinida de dx?',
    options: ['0 + C', 'x + C', 'x²/2 + C', '1/x + C'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'media',
    prompt: 'Qual é a derivada de cos(x)?',
    options: ['sen(x)', '-sen(x)', 'cos(x)', '-cos(x)'],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'media',
    prompt: 'Qual é a derivada de ln(x), para x > 0?',
    options: ['1/x', 'ln(x)/x', 'x·ln(x)', 'e^x'],
    answer: 0,
  },
  {
    theme: 'calculo',
    difficulty: 'media',
    prompt: 'Pela regra da cadeia, como se calcula a derivada de f(g(x))?',
    options: ["f'(x) · g'(x)", "f'(g(x)) · g'(x)", "f'(g'(x))", "f(g'(x))"],
    answer: 1,
  },
  {
    theme: 'calculo',
    difficulty: 'dificil',
    prompt: 'Qual é a integral indefinida de 1/x dx, para x > 0?',
    options: ['ln(x) + C', '1/x² + C', '-1/x² + C', 'x·ln(x) + C'],
    answer: 0,
  },
  {
    theme: 'calculo',
    difficulty: 'dificil',
    prompt: 'Pela regra do quociente, a derivada de f(x)/g(x) é:',
    options: [
      "(f'·g + f·g') / g²",
      "f' / g'",
      "(f'·g - f·g') / g²",
      "(f·g' - f'·g) / g²",
    ],
    answer: 2,
  },
  {
    theme: 'calculo',
    difficulty: 'dificil',
    prompt: 'Uma função f é contínua em x = a quando:',
    options: [
      'f(a) existe, ainda que o limite não exista',
      'o limite de f em a existe e é igual a f(a)',
      'a derivada de f em a existe',
      'apenas o limite lateral à direita existe',
    ],
    answer: 1,
  },

  // ── IA / ML ───────────────────────────────────────────────────────────────
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'Aprendizado supervisionado precisa de dados:',
    options: [
      'Rotulados',
      'Sem rótulo nenhum',
      'Sempre numéricos',
      'Gerados aleatoriamente',
    ],
    answer: 0,
  },
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'O que caracteriza o overfitting?',
    options: [
      'O modelo vai mal no treino e no teste',
      'O modelo vai muito bem no treino e mal em dados novos',
      'O modelo treina rápido demais',
      'O modelo usa poucos dados de teste',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'O algoritmo K-means pertence a qual categoria?',
    options: [
      'Aprendizado supervisionado',
      'Aprendizado não supervisionado',
      'Aprendizado por reforço',
      'Busca heurística',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'Qual destes é um problema de classificação?',
    options: [
      'Prever o preço de um imóvel',
      'Prever se um e-mail é spam ou não',
      'Agrupar clientes parecidos',
      'Reduzir a dimensão dos dados',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'media',
    prompt: 'Para que serve separar os dados em treino e teste?',
    options: [
      'Para o treino ficar mais rápido',
      'Para estimar o desempenho em dados nunca vistos',
      'Para equilibrar as classes',
      'Para evitar dados faltantes',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'media',
    prompt:
      'Qual função de ativação é usada na saída para gerar uma probabilidade em classificação binária?',
    options: ['ReLU', 'Sigmoide', 'Tangente hiperbólica', 'Linear'],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'media',
    prompt: 'Na matriz de confusão, um falso positivo é quando o modelo:',
    options: [
      'Previu positivo e o caso era negativo',
      'Previu negativo e o caso era positivo',
      'Acertou um caso positivo',
      'Acertou um caso negativo',
    ],
    answer: 0,
  },
  {
    theme: 'ia-ml',
    difficulty: 'dificil',
    prompt:
      'Em uma base muito desbalanceada, qual métrica é mais informativa que a acurácia?',
    options: [
      'F1-score',
      'Erro quadrático médio',
      'Número de épocas',
      'Perplexidade',
    ],
    answer: 0,
  },
  {
    theme: 'ia-ml',
    difficulty: 'dificil',
    prompt: 'O que o backpropagation faz em uma rede neural?',
    options: [
      'Inicializa os pesos aleatoriamente',
      'Propaga o gradiente do erro para ajustar os pesos',
      'Normaliza os dados de entrada',
      'Escolhe a arquitetura da rede',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'dificil',
    prompt: 'Para que serve a regularização L2 (ridge)?',
    options: [
      'Aumentar a capacidade do modelo',
      'Penalizar pesos grandes e reduzir o overfitting',
      'Acelerar a convergência do gradiente',
      'Balancear as classes do conjunto',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'O que caracteriza o underfitting?',
    options: [
      'O modelo decora o conjunto de treino',
      'O modelo é simples demais e erra até no treino',
      'O modelo dispensa dados rotulados',
      'O modelo tem acurácia perfeita',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'O que é uma feature em aprendizado de máquina?',
    options: [
      'Um atributo de entrada usado pelo modelo',
      'O valor que o modelo prevê',
      'O erro cometido pelo modelo',
      'O número de camadas da rede',
    ],
    answer: 0,
  },
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'Qual destes é um problema de regressão?',
    options: [
      'Dizer se um e-mail é spam',
      'Classificar fotos em cão ou gato',
      'Prever o preço de um imóvel',
      'Agrupar clientes parecidos',
    ],
    answer: 2,
  },
  {
    theme: 'ia-ml',
    difficulty: 'facil',
    prompt: 'Um conjunto de dados rotulado é exigido por qual abordagem?',
    options: [
      'Aprendizado supervisionado',
      'Aprendizado não supervisionado',
      'Agrupamento',
      'Redução de dimensionalidade',
    ],
    answer: 0,
  },
  {
    theme: 'ia-ml',
    difficulty: 'media',
    prompt: 'O que a acurácia de um classificador mede?',
    options: [
      'A proporção de previsões corretas sobre o total',
      'Apenas os acertos da classe positiva',
      'O erro médio quadrático',
      'O tempo gasto no treino',
    ],
    answer: 0,
  },
  {
    theme: 'ia-ml',
    difficulty: 'media',
    prompt: 'O que a validação cruzada (cross-validation) estima?',
    options: [
      'O tamanho ideal do conjunto de dados',
      'O desempenho do modelo usando várias divisões dos dados',
      'O número mínimo de atributos necessários',
      'O rótulo correto de cada exemplo não rotulado',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'media',
    prompt: 'O que é a taxa de aprendizado (learning rate)?',
    options: [
      'A porcentagem de dados separada para treino',
      'A acurácia mínima aceita',
      'O tamanho do passo na atualização dos pesos',
      'O número de épocas de treino',
    ],
    answer: 2,
  },
  {
    theme: 'ia-ml',
    difficulty: 'dificil',
    prompt: 'Na matriz de confusão, o que o recall (revocação) mede?',
    options: [
      'A fração dos positivos reais que o modelo encontrou',
      'A fração das previsões positivas que estavam certas',
      'O total de acertos sobre o total de exemplos',
      'O erro absoluto médio',
    ],
    answer: 0,
  },
  {
    theme: 'ia-ml',
    difficulty: 'dificil',
    prompt: 'Para que serve a função de ativação em uma rede neural?',
    options: [
      'Normalizar os dados de entrada',
      'Introduzir não linearidade entre as camadas',
      'Reduzir o número de neurônios',
      'Calcular o gradiente automaticamente',
    ],
    answer: 1,
  },
  {
    theme: 'ia-ml',
    difficulty: 'dificil',
    prompt: 'O que o gradiente descendente faz durante o treino?',
    options: [
      'Sorteia os pesos iniciais da rede',
      'Ajusta os pesos na direção que reduz a função de perda',
      'Aumenta a função de perda para explorar o espaço',
      'Remove os atributos irrelevantes',
    ],
    answer: 1,
  },

  // ── Robótica ──────────────────────────────────────────────────────────────
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Qual componente converte sinal elétrico em movimento?',
    options: ['Sensor', 'Atuador', 'Resistor', 'Barramento'],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Um sensor ultrassônico mede principalmente:',
    options: ['Temperatura', 'Distância', 'Luminosidade', 'Corrente elétrica'],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Para que serve um encoder acoplado a um motor?',
    options: [
      'Aumentar o torque',
      'Medir rotação e posição do eixo',
      'Filtrar ruído elétrico',
      'Converter tensão em corrente',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'O que um servo motor controla diretamente?',
    options: [
      'A posição angular',
      'A temperatura do circuito',
      'A tensão da fonte',
      'A frequência do clock',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Em um controlador PID, o termo integral (I) corrige:',
    options: [
      'O erro instantâneo',
      'O erro acumulado ao longo do tempo',
      'A velocidade de variação do erro',
      'O ruído do sensor',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Para que serve o PWM no controle de motores?',
    options: [
      'Inverter o sentido de rotação',
      'Controlar a potência média variando a largura do pulso',
      'Medir a corrente do motor',
      'Converter sinal analógico em digital',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'O que são os graus de liberdade de um braço robótico?',
    options: [
      'O número de motores instalados',
      'O número de movimentos independentes possíveis',
      'O alcance máximo em metros',
      'A carga máxima suportada',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O que a cinemática inversa calcula?',
    options: [
      'A posição da garra a partir dos ângulos das juntas',
      'Os ângulos das juntas a partir da posição desejada da garra',
      'A força necessária em cada junta',
      'A trajetória de menor consumo de energia',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt:
      'Qual barramento é o padrão de comunicação entre módulos em veículos e automação industrial?',
    options: ['CAN', 'HDMI', 'SATA', 'VGA'],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O termo derivativo (D) de um PID reage a quê?',
    options: [
      'Ao valor absoluto do erro',
      'À taxa de variação do erro, amortecendo oscilações',
      'À soma histórica do erro',
      'Ao valor de referência',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'O que um atuador faz em um robô?',
    options: [
      'Converte um comando em ação física',
      'Mede grandezas do ambiente',
      'Armazena o programa em execução',
      'Comunica o robô com a rede',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Para que serve um motor de passo?',
    options: [
      'Medir a temperatura do circuito',
      'Girar em incrementos angulares precisos',
      'Gerar energia para os sensores',
      'Amplificar o sinal do encoder',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Qual é a função do microcontrolador em um robô?',
    options: [
      'Fornecer torque ao eixo',
      'Isolar o circuito de potência',
      'Executar o programa e comandar os periféricos',
      'Medir a distância até o obstáculo',
    ],
    answer: 2,
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Um sensor de proximidade indutivo detecta:',
    options: [
      'A presença de objetos metálicos sem contato',
      'A temperatura da superfície',
      'A cor do objeto à frente',
      'A carga restante da bateria',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Em um controlador PID, o termo proporcional (P) reage a quê?',
    options: [
      'Ao erro atual',
      'Ao acúmulo do erro ao longo do tempo',
      'À velocidade de variação do erro',
      'Apenas ao valor desejado',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'O que é odometria em um robô móvel?',
    options: [
      'Detectar obstáculos por ultrassom',
      'Planejar a trajetória de menor custo',
      'Estimar a posição a partir do movimento das rodas',
      'Controlar a corrente do motor',
    ],
    answer: 2,
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Para que serve uma ponte H no acionamento de um motor?',
    options: [
      'Inverter o sentido de rotação',
      'Medir a corrente consumida',
      'Converter sinal analógico em digital',
      'Alimentar os sensores em 3,3 V',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O que a cinemática direta calcula?',
    options: [
      'Os ângulos das juntas a partir da posição desejada',
      'A posição do efetuador a partir dos ângulos das juntas',
      'A força necessária em cada junta',
      'O tempo de resposta do controlador',
    ],
    answer: 1,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'Por que um controle em malha fechada usa realimentação?',
    options: [
      'Para corrigir o comando a partir do erro medido',
      'Para dispensar o uso de sensores',
      'Para reduzir o consumo do motor',
      'Para acelerar o processamento do microcontrolador',
    ],
    answer: 0,
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O que é o espaço de configuração de um robô?',
    options: [
      'A área física ocupada pela base',
      'A memória disponível no controlador',
      'O conjunto de todas as posições possíveis das juntas',
      'A faixa de tensão de operação',
    ],
    answer: 2,
  },

  // ── Arquitetura ───────────────────────────────────────────────────────────
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual unidade da CPU executa as operações aritméticas e lógicas?',
    options: ['ULA', 'Cache', 'Barramento', 'Controlador de memória'],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual é a memória mais rápida e mais próxima do núcleo da CPU?',
    options: ['Registradores', 'Cache L3', 'Memória RAM', 'SSD'],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Quantos bits tem 1 byte?',
    options: ['4', '8', '16', '32'],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'A memória RAM é classificada como:',
    options: [
      'Volátil (perde o conteúdo sem energia)',
      'Não volátil',
      'Somente leitura',
      'Memória secundária',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Para que serve o pipeline de instruções?',
    options: [
      'Reduzir o consumo de energia',
      'Sobrepor as etapas de várias instruções e aumentar a vazão',
      'Aumentar o tamanho da cache',
      'Executar instruções fora de ordem',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que caracteriza uma arquitetura RISC frente a uma CISC?',
    options: [
      'Instruções mais numerosas e complexas',
      'Conjunto de instruções reduzido e regular',
      'Ausência de registradores',
      'Execução exclusivamente sequencial',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que significa um cache miss?',
    options: [
      'A cache foi corrompida',
      'O dado não estava na cache e precisou ser buscado na memória',
      'A cache está desativada',
      'A instrução foi descartada',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Quando ocorre um hazard de dados no pipeline?',
    options: [
      'Quando duas instruções usam a mesma unidade funcional',
      'Quando uma instrução depende de um resultado ainda não disponível',
      'Quando um desvio é previsto incorretamente',
      'Quando a memória está cheia',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'O princípio da localidade temporal diz que:',
    options: [
      'Endereços vizinhos tendem a ser acessados juntos',
      'Um dado acessado tende a ser acessado de novo em breve',
      'Instruções são executadas em ordem',
      'A cache deve ser esvaziada periodicamente',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'A Lei de Amdahl mostra que o ganho ao paralelizar é limitado:',
    options: [
      'Pela quantidade de memória disponível',
      'Pela fração do programa que continua sequencial',
      'Pela frequência do processador',
      'Pelo número de instruções do programa',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Quantos bytes tem 1 kibibyte (KiB)?',
    options: ['512', '1000', '1024', '2048'],
    answer: 2,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual registrador guarda o endereço da próxima instrução?',
    options: [
      'O contador de programa (PC)',
      'A unidade lógica e aritmética',
      'O cache L2',
      'O barramento de dados',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'A memória ROM caracteriza-se por:',
    options: [
      'Ser mais rápida que o cache L1',
      'Não perder o conteúdo ao desligar o computador',
      'Ser volátil como a RAM',
      'Existir apenas em servidores',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'O que trafega pelo barramento de dados?',
    options: [
      'Apenas endereços de memória',
      'Apenas sinais de controle',
      'Os valores lidos e escritos na memória',
      'A energia vinda da fonte',
    ],
    answer: 2,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que caracteriza a arquitetura de von Neumann?',
    options: [
      'Dados e instruções compartilham a mesma memória',
      'Dados e instruções ficam em memórias fisicamente separadas',
      'Não existe unidade de controle',
      'O processador é obrigatoriamente multinúcleo',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Quando ocorre um cache hit?',
    options: [
      'Quando o dado precisa ser buscado na memória principal',
      'Quando o dado procurado já está no cache',
      'Quando o pipeline é esvaziado',
      'Quando há erro de paridade na memória',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O que a memória virtual oferece a cada processo?',
    options: [
      'Uma frequência de operação maior no processador',
      'Um substituto para o cache L1 em sistemas antigos',
      'Um espaço de endereços maior que a RAM física disponível',
      'Um barramento de endereços dedicado',
    ],
    answer: 2,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'O princípio da localidade espacial diz que:',
    options: [
      'Endereços vizinhos ao acessado tendem a ser acessados em seguida',
      'O mesmo endereço tende a ser acessado de novo em breve',
      'O cache precisa ser maior que a memória principal',
      'As instruções são sempre executadas fora de ordem',
    ],
    answer: 0,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Um hazard de controle no pipeline é causado por:',
    options: [
      'Duas instruções que disputam o mesmo registrador',
      'Desvios condicionais cujo destino ainda não é conhecido',
      'Falta de energia no barramento',
      'Um cache totalmente associativo',
    ],
    answer: 1,
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Para que serve a previsão de desvio (branch prediction)?',
    options: [
      'Reduzir o consumo de energia da ULA',
      'Aumentar o tamanho efetivo do cache',
      'Ordenar os acessos à memória principal',
      'Evitar bolhas no pipeline antecipando o caminho do desvio',
    ],
    answer: 3,
  },

  // ── NPI ───────────────────────────────────────────────────────────────────
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'Qual é o objetivo principal de um code review?',
    options: [
      'Encontrar problemas e compartilhar conhecimento antes do merge',
      'Definir quem é responsável pelos erros',
      'Substituir os testes automatizados',
      'Acelerar a entrega pulando etapas',
    ],
    answer: 0,
  },
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'O que é um MVP em desenvolvimento de produto?',
    options: [
      'A versão final com todas as funcionalidades',
      'A menor versão que entrega valor e permite aprender com o uso',
      'Um protótipo descartável de interface',
      'O documento de requisitos aprovado',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'Para que serve a reunião diária de acompanhamento?',
    options: [
      'Prestar contas para a gestão',
      'Alinhar o time e destravar impedimentos',
      'Distribuir tarefas novas todo dia',
      'Revisar o código entregue',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'Qual é a função de um sistema de controle de versão?',
    options: [
      'Compilar o projeto automaticamente',
      'Registrar o histórico e permitir trabalho em paralelo',
      'Hospedar o site em produção',
      'Gerar a documentação do código',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'media',
    prompt: 'O que é a "definição de pronto" (Definition of Done)?',
    options: [
      'O prazo combinado com o cliente',
      'O critério acordado do que precisa estar feito para a entrega contar',
      'A lista de tarefas da sprint',
      'O aceite formal do usuário final',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'media',
    prompt: 'Por que pull requests pequenos são preferíveis?',
    options: [
      'Ocupam menos espaço no repositório',
      'São revisados com mais atenção e carregam menos risco',
      'Dispensam testes automatizados',
      'Permitem pular o code review',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'media',
    prompt: 'O que é o backlog de um projeto?',
    options: [
      'O registro de bugs já corrigidos',
      'A lista priorizada do que ainda falta fazer',
      'O histórico de commits',
      'A documentação de arquitetura',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'dificil',
    prompt: 'O que é débito técnico?',
    options: [
      'O custo de licenças de software do projeto',
      'Um atalho que acelera agora e cobra manutenção depois',
      'O tempo gasto em reuniões',
      'A diferença entre o prazo estimado e o real',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'dificil',
    prompt: 'Qual é o foco de uma retrospectiva de time?',
    options: [
      'Avaliar o desempenho individual de cada pessoa',
      'Melhorar o processo de trabalho do time',
      'Replanejar o escopo do produto',
      'Apresentar resultados para o cliente',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'dificil',
    prompt: 'Qual é a diferença entre entrega contínua e implantação contínua?',
    options: [
      'Não há diferença, são sinônimos',
      'Na implantação contínua todo commit aprovado vai a produção automaticamente',
      'A entrega contínua dispensa testes',
      'A implantação contínua exige aprovação manual de cada versão',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'O que é um commit em um sistema de controle de versão?',
    options: [
      'Um conjunto de alterações registrado no histórico',
      'Uma cópia completa do repositório remoto',
      'Um conflito entre duas branches',
      'Um arquivo de configuração do projeto',
    ],
    answer: 0,
  },
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'Para que serve criar uma branch?',
    options: [
      'Apagar o histórico do projeto',
      'Isolar um trabalho em andamento da linha principal',
      'Publicar o sistema em produção',
      'Executar os testes automatizados',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'O que é um requisito funcional?',
    options: [
      'Quão rápido o sistema deve responder',
      'O orçamento previsto para o projeto',
      'O que o sistema deve fazer',
      'A linguagem de programação escolhida',
    ],
    answer: 2,
  },
  {
    theme: 'npi',
    difficulty: 'facil',
    prompt: 'Qual é o papel de um protótipo?',
    options: [
      'Validar uma ideia antes de construí-la por inteiro',
      'Substituir a documentação do sistema',
      'Encerrar formalmente o projeto',
      'Medir a cobertura dos testes',
    ],
    answer: 0,
  },
  {
    theme: 'npi',
    difficulty: 'media',
    prompt: 'O que caracteriza um requisito NÃO funcional?',
    options: [
      'Descreve uma tela específica do sistema',
      'Descreve qualidades como desempenho, segurança e usabilidade',
      'É sempre opcional para a entrega',
      'Só se aplica a bancos de dados',
    ],
    answer: 1,
  },
  {
    theme: 'npi',
    difficulty: 'media',
    prompt: 'Para que serve a integração contínua?',
    options: [
      'Publicar o aplicativo nas lojas',
      'Escrever a documentação do usuário',
      'Integrar e testar as mudanças automaticamente a cada envio',
      'Priorizar os itens do backlog',
    ],
    answer: 2,
  },
  {
    theme: 'npi',
    difficulty: 'media',
    prompt: 'O que é um conflito de merge?',
    options: [
      'Duas alterações no mesmo trecho que o versionador não sabe unir',
      'Um teste automatizado que falhou',
      'Uma branch criada sem nenhum commit',
      'Um repositório local sem remoto configurado',
    ],
    answer: 0,
  },
  {
    theme: 'npi',
    difficulty: 'dificil',
    prompt: 'Por que testes automatizados reduzem o custo de mudança?',
    options: [
      'Porque substituem o code review',
      'Porque dispensam o levantamento de requisitos',
      'Porque detectam regressões cedo, quando corrigir ainda é barato',
      'Porque diminuem o tamanho dos commits',
    ],
    answer: 2,
  },
  {
    theme: 'npi',
    difficulty: 'dificil',
    prompt: 'O que caracteriza o scope creep em um projeto?',
    options: [
      'Novas exigências entram sem replanejar prazo e esforço',
      'O escopo é fechado em contrato antes de começar',
      'O time entrega antes do prazo combinado',
      'O backlog está priorizado e revisado',
    ],
    answer: 0,
  },
  {
    theme: 'npi',
    difficulty: 'dificil',
    prompt: 'Qual é o propósito de uma prova de conceito (PoC)?',
    options: [
      'Entregar o produto final ao cliente',
      'Verificar se uma abordagem técnica é viável',
      'Documentar um sistema já pronto',
      'Treinar os usuários finais',
    ],
    answer: 1,
  },

  // ── Redes ─────────────────────────────────────────────────────────────────
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual protocolo traduz nomes de domínio em endereços IP?',
    options: ['DHCP', 'DNS', 'FTP', 'SMTP'],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual é a porta padrão do HTTPS?',
    options: ['21', '80', '443', '8080'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'O protocolo TCP é:',
    options: [
      'Orientado a conexão e confiável',
      'Sem conexão e sem garantias',
      'Exclusivo de redes sem fio',
      'Usado apenas para streaming',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'O que é um endereço IP?',
    options: [
      'O identificador do dispositivo na rede',
      'O número de série do equipamento',
      'A senha de acesso ao roteador',
      'O nome do domínio do site',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Qual é a principal diferença do UDP para o TCP?',
    options: [
      'O UDP é mais lento',
      'O UDP não garante entrega nem ordem dos pacotes',
      'O UDP só funciona em rede local',
      'O UDP criptografa os dados',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Em qual camada do modelo OSI atua um roteador?',
    options: ['Física (1)', 'Enlace (2)', 'Rede (3)', 'Transporte (4)'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'O que o NAT faz?',
    options: [
      'Criptografa o tráfego de saída',
      'Traduz endereços privados em um endereço público',
      'Distribui endereços IP na rede local',
      'Resolve nomes de domínio',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Qual é a sequência do three-way handshake do TCP?',
    options: [
      'SYN, ACK, FIN',
      'SYN, SYN-ACK, ACK',
      'ACK, SYN, ACK',
      'SYN, FIN, ACK',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Quantos endereços de host utilizáveis tem uma sub-rede /24?',
    options: ['128', '254', '255', '256'],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Para que serve o campo TTL de um pacote IP?',
    options: [
      'Definir a prioridade do pacote',
      'Impedir que pacotes circulem indefinidamente em loops',
      'Indicar o tamanho do pacote',
      'Identificar o protocolo de transporte',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual é a porta padrão do HTTP?',
    options: ['21', '25', '80', '443'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'O que um servidor DHCP faz?',
    options: [
      'Distribui endereços IP automaticamente na rede',
      'Traduz nomes de domínio em endereços',
      'Filtra pacotes maliciosos',
      'Criptografa todo o tráfego da rede',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'A que corresponde o endereço 127.0.0.1?',
    options: [
      'Ao gateway padrão da rede',
      'Ao próprio host (loopback)',
      'Ao servidor DNS público',
      'Ao endereço de broadcast',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual dispositivo interliga redes diferentes?',
    options: ['O repetidor', 'O switch', 'O roteador', 'O hub'],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Em qual camada do modelo OSI atua um switch?',
    options: [
      'Camada 1 (física)',
      'Camada 2 (enlace)',
      'Camada 3 (rede)',
      'Camada 4 (transporte)',
    ],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'O que o protocolo ARP resolve?',
    options: [
      'O endereço MAC correspondente a um endereço IP',
      'O nome de domínio correspondente a um IP',
      'A melhor rota até o destino',
      'A porta usada por um serviço',
    ],
    answer: 0,
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Para que serve uma VLAN?',
    options: [
      'Aumentar a velocidade nominal do cabo',
      'Criptografar o tráfego dentro do switch',
      'Separar logicamente redes que compartilham o mesmo switch',
      'Substituir o roteador de borda',
    ],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Quantos endereços de host utilizáveis tem uma sub-rede /26?',
    options: ['30', '62', '64', '126'],
    answer: 1,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'O que o TLS acrescenta ao HTTP?',
    options: [
      'Compressão dos dados transmitidos',
      'Roteamento entre redes distintas',
      'Confidencialidade e autenticação do servidor',
      'Controle de congestionamento',
    ],
    answer: 2,
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Para que serve o controle de congestionamento do TCP?',
    options: [
      'Ajustar a taxa de envio ao que a rede suporta',
      'Garantir a ordem de entrega dos pacotes',
      'Traduzir endereços privados em públicos',
      'Descobrir a rota mais curta até o destino',
    ],
    answer: 0,
  },

  // ── Banco de Dados ────────────────────────────────────────────────────────
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando SQL é usado para consultar dados?',
    options: ['INSERT', 'SELECT', 'UPDATE', 'CREATE'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Para que serve uma chave primária?',
    options: [
      'Identificar unicamente cada linha da tabela',
      'Ordenar os resultados da consulta',
      'Ligar o banco à aplicação',
      'Criptografar a coluna',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando remove linhas de uma tabela?',
    options: ['DROP', 'DELETE', 'REMOVE', 'TRUNCATE COLUMN'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Em um banco relacional, uma tabela é composta por:',
    options: [
      'Linhas e colunas',
      'Documentos e coleções',
      'Chaves e valores',
      'Nós e arestas',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'O que um INNER JOIN retorna?',
    options: [
      'Todas as linhas das duas tabelas',
      'Apenas as linhas com correspondência nas duas tabelas',
      'Todas as linhas da tabela da esquerda',
      'As linhas sem correspondência',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Para que serve um índice em uma tabela?',
    options: [
      'Reduzir o espaço ocupado pelos dados',
      'Acelerar as buscas, ao custo de escrita e espaço',
      'Garantir que os dados não se repitam',
      'Fazer backup automático das linhas',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'O que uma chave estrangeira garante?',
    options: [
      'A ordenação das linhas',
      'A integridade referencial entre tabelas',
      'A unicidade da coluna',
      'A criptografia do relacionamento',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Nas propriedades ACID, o que significa o "I"?',
    options: ['Integridade', 'Isolamento', 'Indexação', 'Imutabilidade'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'O que um LEFT JOIN retorna?',
    options: [
      'Só as linhas com correspondência',
      'Todas as linhas da tabela da esquerda, com NULL onde não há par',
      'Todas as linhas das duas tabelas',
      'As linhas duplicadas da direita',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'A terceira forma normal (3FN) elimina:',
    options: [
      'Grupos repetitivos',
      'Dependências parciais da chave',
      'Dependências transitivas entre atributos não-chave',
      'Chaves estrangeiras redundantes',
    ],
    answer: 2,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando SQL insere novas linhas em uma tabela?',
    options: ['INSERT', 'SELECT', 'UPDATE', 'DROP'],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando SQL altera dados já existentes?',
    options: ['SELECT', 'UPDATE', 'INSERT', 'CREATE'],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'O que a cláusula WHERE faz em um SELECT?',
    options: [
      'Ordena o resultado',
      'Agrupa as linhas por um campo',
      'Filtra quais linhas entram no resultado',
      'Junta duas tabelas',
    ],
    answer: 2,
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Em SQL, o que o valor NULL representa?',
    options: [
      'Ausência de valor',
      'O número zero',
      'Uma string vazia',
      'O valor booleano falso',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Para que serve a cláusula GROUP BY?',
    options: [
      'Ordenar o resultado da consulta',
      'Agrupar linhas para aplicar funções de agregação',
      'Remover linhas duplicadas do filtro',
      'Criar um índice na tabela',
    ],
    answer: 1,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'O que a cláusula ORDER BY faz?',
    options: [
      'Filtra as linhas do resultado',
      'Agrupa as linhas por um campo',
      'Ordena as linhas do resultado',
      'Limita a quantidade de linhas retornadas',
    ],
    answer: 2,
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Qual é a diferença entre DELETE e TRUNCATE?',
    options: [
      'DELETE remove linhas com filtro; TRUNCATE esvazia a tabela inteira',
      'TRUNCATE aceita WHERE e DELETE não',
      'DELETE apaga a tabela; TRUNCATE apaga o banco',
      'Não há diferença entre os dois',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Nas propriedades ACID, o que significa o "A"?',
    options: [
      'Acessibilidade dos dados a qualquer usuário',
      'Auditoria de todas as operações',
      'Alta disponibilidade do servidor',
      'Atomicidade: a transação vale por inteiro ou não vale',
    ],
    answer: 3,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'O que a segunda forma normal (2FN) exige?',
    options: [
      'Que todo atributo não chave dependa da chave primária inteira',
      'Que nenhuma coluna aceite valores nulos',
      'Que exista um índice em cada coluna',
      'Que a tabela tenha no máximo dez colunas',
    ],
    answer: 0,
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Por que um índice pode deixar a escrita mais lenta?',
    options: [
      'Porque bloqueia a tabela inteira a cada consulta',
      'Porque cada gravação precisa atualizar também a estrutura do índice',
      'Porque duplica todas as linhas da tabela',
      'Porque desativa o cache do banco',
    ],
    answer: 1,
  },

  // ── Algoritmos ────────────────────────────────────────────────────────────
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é a complexidade da busca binária?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Qual estrutura de dados segue a regra "último a entrar, primeiro a sair"?',
    options: ['Fila', 'Pilha', 'Lista ligada', 'Árvore'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Qual estrutura de dados segue a regra "primeiro a entrar, primeiro a sair"?',
    options: ['Pilha', 'Fila', 'Grafo', 'Tabela hash'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Na busca linear em uma lista de n elementos, quantas comparações o pior caso exige?',
    options: ['1', 'log n', 'n', 'n²'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a complexidade do quicksort no caso médio?',
    options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'O que toda função recursiva precisa ter para terminar?',
    options: [
      'Um caso base',
      'Um laço de repetição',
      'Uma variável global',
      'Um vetor auxiliar',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é o pré-requisito para aplicar busca binária?',
    options: [
      'A lista precisa estar ordenada',
      'A lista precisa ter tamanho par',
      'Os elementos precisam ser numéricos',
      'A lista precisa caber na memória cache',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Qual é a complexidade do quicksort no pior caso?',
    options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'O que a programação dinâmica evita?',
    options: [
      'O uso de recursão',
      'O recálculo de subproblemas que já foram resolvidos',
      'A alocação de memória extra',
      'O uso de estruturas ordenadas',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Qual é a complexidade média de inserção em uma tabela hash?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt:
      'Qual é a complexidade de acessar um elemento de um vetor pelo índice?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'O que cada nó de uma lista encadeada guarda?',
    options: [
      'Apenas o valor armazenado',
      'O valor e a referência para o próximo nó',
      'O índice e o tamanho da lista',
      'Uma cópia do vetor inteiro',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é a complexidade do bubble sort no pior caso?',
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(n²)'],
    answer: 3,
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'O que um algoritmo de ordenação faz?',
    options: [
      'Organiza os elementos segundo um critério',
      'Remove os elementos repetidos',
      'Localiza um elemento específico',
      'Conta quantos elementos existem',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a complexidade do merge sort em qualquer caso?',
    options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Em uma árvore binária de busca equilibrada, quanto custa a busca?',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Como um algoritmo guloso (greedy) toma cada decisão?',
    options: [
      'Escolhe o melhor local a cada passo, sem revisar a decisão',
      'Testa todas as combinações possíveis',
      'Divide o problema ao meio a cada chamada',
      'Guarda a solução de cada subproblema resolvido',
    ],
    answer: 0,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt:
      'Qual é a complexidade de inserir no início de uma lista encadeada?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'],
    answer: 2,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'O que a notação O(f(n)) descreve?',
    options: [
      'O tempo exato de execução em segundos',
      'Um limite superior para o crescimento do custo',
      'O consumo de memória, e apenas ele',
      'O número de linhas do código-fonte',
    ],
    answer: 1,
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt:
      'Qual é a diferença entre busca em largura (BFS) e em profundidade (DFS)?',
    options: [
      'BFS usa pilha e DFS usa fila',
      'BFS só funciona em árvores; DFS, em grafos',
      'BFS explora por níveis; DFS desce por um ramo até o fim',
      'DFS sempre encontra o caminho mais curto',
    ],
    answer: 2,
  },
];
