/**
 * Banco de questões do Quiz TREINO.
 *
 * Semeado por `npm run db:seed-quiz-treino` na tabela `training_questions`,
 * que é separada de `quiz_questions` de propósito — ver docs/QUIZ.md.
 *
 * Estas questões NÃO valem captura. É isso que permite o gabarito ir para o
 * cliente e a revisão ser por amostragem; o banco oficial continua sendo
 * escrito e revisado questão por questão, porque lá um erro custa um QR
 * indevido.
 *
 * Para ampliar ou regenerar um tema:
 *   ANTHROPIC_API_KEY=... npm run gen:quiz-treino -- --tema=logica
 * O script valida o formato e recusa duplicatas; revise por amostragem antes
 * de semear.
 */
import type { QuizSeedQuestion } from './quiz-questions';

export interface TrainingSeedQuestion extends QuizSeedQuestion {
  /** Uma frase explicando a resposta, mostrada no feedback imediato. */
  explanation: string;
}

export const TRAINING_QUESTIONS: TrainingSeedQuestion[] = [
  // ── Humanas ───────────────────────────────────────────────────────────────────
  // Humanas aqui é humanas APLICADA à computação: ética, LGPD, impacto social e
  // método científico — o mesmo recorte do banco oficial.
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'O que significa a sigla LGPD?',
    options: [
      'Lei Geral de Publicidade Digital',
      'Lei Geral de Proteção de Dados',
      'Lei de Governança de Processos Digitais',
      'Lei Geral de Privacidade Documental',
    ],
    answer: 1,
    explanation:
      'É a Lei Geral de Proteção de Dados (13.709/2018), que regula o tratamento de dados pessoais no Brasil.',
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'O e-mail pessoal de alguém é considerado dado pessoal?',
    options: [
      'Sim, porque permite identificar a pessoa',
      'Não, porque é público',
      'Só se estiver junto do CPF',
      'Só se for e-mail corporativo',
    ],
    answer: 0,
    explanation:
      'Dado pessoal é toda informação que identifica ou torna identificável uma pessoa — o e-mail se encaixa.',
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'Copiar um trecho da internet no trabalho sem citar a fonte é o quê?',
    options: ['Paráfrase', 'Resenha', 'Plágio', 'Citação direta'],
    answer: 2,
    explanation:
      'Usar a produção de outra pessoa sem atribuir a autoria é plágio, mesmo que o trecho seja curto.',
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt:
      'Fazer um site funcionar bem com leitor de tela atende a qual objetivo?',
    options: [
      'Acessibilidade',
      'Escalabilidade',
      'Portabilidade',
      'Confidencialidade',
    ],
    answer: 0,
    explanation:
      'Acessibilidade é garantir que pessoas com deficiência consigam perceber, navegar e usar o sistema.',
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'Quem pode pedir a exclusão dos seus dados guardados por uma empresa?',
    options: [
      'Somente um juiz',
      'Qualquer funcionário da empresa',
      'O próprio titular dos dados',
      'Apenas o órgão regulador',
    ],
    answer: 2,
    explanation:
      'A LGPD dá ao titular o direito de solicitar eliminação dos dados tratados com base no seu consentimento.',
  },
  {
    theme: 'humanas',
    difficulty: 'facil',
    prompt: 'Para que serve a licença de um projeto de código aberto?',
    options: [
      'Garantir que o código nunca será alterado',
      'Definir o que outras pessoas podem fazer com aquele código',
      'Registrar o projeto no cartório',
      'Impedir a cópia do repositório',
    ],
    answer: 1,
    explanation:
      'A licença estabelece os direitos de uso, modificação e redistribuição; sem ela, o padrão é "todos os direitos reservados".',
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt:
      'Um chatbot treinado só com textos de um único grupo social tende a fazer o quê?',
    options: [
      'Responder mais rápido',
      'Reproduzir o ponto de vista daquele grupo',
      'Consumir menos memória',
      'Recusar perguntas longas',
    ],
    answer: 1,
    explanation:
      'O modelo aprende o que está nos dados: base pouco diversa gera respostas enviesadas em favor do grupo representado.',
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt: 'Quais destes a LGPD classifica como dados pessoais SENSÍVEIS?',
    options: [
      'Nome completo e endereço',
      'Número de telefone e e-mail',
      'Origem racial, religião, saúde e biometria',
      'Histórico de compras numa loja',
    ],
    answer: 2,
    explanation:
      'Dados sensíveis recebem proteção reforçada porque seu uso indevido facilita discriminação.',
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt:
      'Um termo de uso longo e cheio de jargão compromete principalmente qual princípio da LGPD?',
    options: ['Transparência', 'Segurança', 'Portabilidade', 'Prevenção'],
    answer: 0,
    explanation:
      'A lei exige informação clara e acessível sobre o tratamento; texto incompreensível esvazia esse direito.',
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt: 'O que um comitê de ética em pesquisa avalia num projeto?',
    options: [
      'A qualidade da escrita do artigo',
      'O orçamento solicitado à agência de fomento',
      'A originalidade do tema escolhido',
      'Os riscos e a proteção dos participantes',
    ],
    answer: 3,
    explanation:
      'O comitê existe para proteger quem participa da pesquisa, analisando riscos, consentimento e privacidade.',
  },
  {
    theme: 'humanas',
    difficulty: 'media',
    prompt:
      'A automação que elimina postos de trabalho inteiros levanta qual discussão?',
    options: [
      'Impacto social da tecnologia',
      'Complexidade algorítmica',
      'Portabilidade de sistemas',
      'Normalização de banco de dados',
    ],
    answer: 0,
    explanation:
      'É um debate clássico de humanas aplicadas: quem ganha e quem perde com a adoção de uma tecnologia.',
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt: 'Qual é a diferença entre pseudonimização e anonimização?',
    options: [
      'São termos equivalentes na LGPD',
      'A pseudonimização ainda permite reverter com informação adicional',
      'A anonimização só vale para dados sensíveis',
      'A pseudonimização exige autorização judicial',
    ],
    answer: 1,
    explanation:
      'Dado pseudonimizado continua sendo dado pessoal, porque existe uma chave capaz de reidentificar o titular.',
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt: 'O que a base legal do "legítimo interesse" exige do controlador?',
    options: [
      'Consentimento por escrito do titular',
      'Autorização prévia da autoridade nacional',
      'Balancear o interesse com os direitos e liberdades do titular',
      'Anonimizar todos os dados antes do uso',
    ],
    answer: 2,
    explanation:
      'O legítimo interesse dispensa consentimento, mas obriga a um teste de balanceamento documentado.',
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt: 'No método científico, o que é uma hipótese?',
    options: [
      'A conclusão final da pesquisa',
      'Uma explicação provisória que pode ser testada',
      'O resumo dos trabalhos já publicados',
      'O conjunto de dados coletados',
    ],
    answer: 1,
    explanation:
      'A hipótese é uma resposta candidata formulada de modo a poder ser confirmada ou refutada por evidência.',
  },
  {
    theme: 'humanas',
    difficulty: 'dificil',
    prompt:
      'Modelos de IA que funcionam como "caixa-preta" agravam qual problema ético?',
    options: [
      'O consumo de energia do treinamento',
      'A velocidade de resposta ao usuário',
      'O custo de armazenamento dos dados',
      'A dificuldade de explicar e responsabilizar a decisão',
    ],
    answer: 3,
    explanation:
      'Sem explicabilidade, quem foi prejudicado não consegue contestar a decisão nem identificar o responsável.',
  },

  // ── Matemática ────────────────────────────────────────────────────────────────
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de f(x) = x³?',
    options: ['3x', '3x²', 'x²', 'x⁴/4'],
    answer: 1,
    explanation: 'Pela regra do expoente, a derivada de xⁿ é n·xⁿ⁻¹.',
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'A derivada de uma função constante é:',
    options: ['A própria constante', 'Zero', 'Um', 'Indefinida'],
    answer: 1,
    explanation: 'Uma constante não varia, então sua taxa de variação é zero.',
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Geometricamente, a derivada num ponto representa:',
    options: [
      'A área sob a curva',
      'A inclinação da reta tangente',
      'O valor máximo da função',
      'A distância até a origem',
    ],
    answer: 1,
    explanation: 'A derivada é o coeficiente angular da tangente naquele ponto.',
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'A integral definida de uma função positiva num intervalo representa:',
    options: [
      'A inclinação média',
      'A área entre a curva e o eixo x',
      'O ponto de máximo',
      'A derivada acumulada',
    ],
    answer: 1,
    explanation: 'A integral definida acumula a área sob a curva no intervalo.',
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Quanto vale o limite de f(x) = 3x quando x tende a 2?',
    options: ['3', '5', '6', 'Não existe'],
    answer: 2,
    explanation: 'A função é contínua, então basta substituir: 3 × 2 = 6.',
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a derivada de f(x) = 5x + 7?',
    options: ['5', '7', '5x', '12'],
    answer: 0,
    explanation: 'A derivada do termo linear é o coeficiente e a da constante é zero.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Se f é derivável e tem máximo local interno em x=c, o que vale?',
    options: [
      "f'(c) > 0",
      "f'(c) < 0",
      "f'(c) = 0",
      "f'(c) não existe",
    ],
    answer: 2,
    explanation: 'Em extremo interno de função derivável a tangente é horizontal.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Pela regra da cadeia, a derivada de f(g(x)) é:',
    options: [
      "f'(x) · g'(x)",
      "f'(g(x)) · g'(x)",
      "f(g'(x))",
      "f'(g'(x))",
    ],
    answer: 1,
    explanation: 'Deriva-se a função de fora aplicada na de dentro e multiplica pela derivada de dentro.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Uma função com derivada segunda positiva num intervalo é:',
    options: [
      'Decrescente',
      'Côncava para cima',
      'Côncava para baixo',
      'Constante',
    ],
    answer: 1,
    explanation: 'A derivada segunda positiva indica concavidade voltada para cima.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Na notação assintótica, por que log(n) cresce mais devagar que n?',
    options: [
      'Porque log(n) é negativo',
      'Porque a razão log(n)/n tende a zero',
      'Porque log(n) é constante',
      'Porque n é sempre inteiro',
    ],
    answer: 1,
    explanation: 'O limite da razão tender a zero é a definição de crescimento estritamente menor.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'A derivada de f(x) = eˣ é:',
    options: ['x·eˣ⁻¹', 'eˣ', '1/x', 'ln(x)'],
    answer: 1,
    explanation: 'A exponencial natural é a função que coincide com a própria derivada.',
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'O Teorema Fundamental do Cálculo relaciona quais duas operações?',
    options: [
      'Limite e continuidade',
      'Derivação e integração',
      'Soma e produto',
      'Máximo e mínimo',
    ],
    answer: 1,
    explanation: 'Ele mostra que integração e derivação são operações inversas uma da outra.',
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'No gradiente descendente, por que se anda no sentido oposto ao gradiente?',
    options: [
      'Porque o gradiente aponta para o maior crescimento',
      'Porque o gradiente é sempre negativo',
      'Para acelerar a convergência apenas',
      'Porque a função é sempre convexa',
    ],
    answer: 0,
    explanation: 'O gradiente aponta na direção de maior aumento, então descer exige inverter o sinal.',
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Uma função contínua num intervalo fechado e limitado garante o quê?',
    options: [
      'Que é derivável',
      'Que atinge máximo e mínimo no intervalo',
      'Que é crescente',
      'Que tem uma única raiz',
    ],
    answer: 1,
    explanation: 'É o Teorema de Weierstrass: continuidade em compacto garante extremos atingidos.',
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Derivada parcial de f(x,y) em relação a x significa derivar tratando y como:',
    options: ['Zero', 'Constante', 'Igual a x', 'Variável livre'],
    answer: 1,
    explanation: 'Na derivada parcial só uma variável varia; as demais ficam congeladas.',
  },

  // Estatística — entrou em Matemática quando o tema passou a cobri-la.
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Qual é a média aritmética entre 10 e 20?',
    options: ['10', '15', '20', '30'],
    answer: 1,
    explanation: 'A média é a soma dividida pela quantidade: (10 + 20) / 2 = 15.',
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'O que a moda indica num conjunto de dados?',
    options: [
      'O valor mais frequente',
      'O valor do meio',
      'A média dos extremos',
      'A soma de todos os valores',
    ],
    answer: 0,
    explanation:
      'Moda é o valor que aparece mais vezes; um conjunto pode ter mais de uma, ou nenhuma.',
  },
  {
    theme: 'matematica',
    difficulty: 'facil',
    prompt: 'Num gráfico de barras de frequência, a barra mais alta corresponde a quê?',
    options: ['À média', 'À mediana', 'À moda', 'Ao desvio padrão'],
    answer: 2,
    explanation:
      'A altura da barra é a frequência, então a mais alta é o valor que mais se repete — a moda.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'O que a variância calcula?',
    options: [
      'A diferença entre o maior e o menor valor',
      'A média dos quadrados dos desvios em relação à média',
      'O valor central dos dados ordenados',
      'A raiz quadrada da média',
    ],
    answer: 1,
    explanation:
      'Elevar os desvios ao quadrado evita que os positivos e negativos se cancelem; o desvio padrão é a raiz dela.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'Se todos os valores de um conjunto são iguais, quanto vale o desvio padrão?',
    options: ['Zero', 'Um', 'A média do conjunto', 'Não é possível calcular'],
    answer: 0,
    explanation:
      'Sem variação não há desvio: todos os valores coincidem com a média e a dispersão é nula.',
  },
  {
    theme: 'matematica',
    difficulty: 'media',
    prompt: 'O que é uma amostra enviesada?',
    options: [
      'Uma amostra com poucos elementos',
      'Uma amostra com valores repetidos',
      'Uma amostra que não representa bem a população',
      'Uma amostra escolhida por sorteio',
    ],
    answer: 2,
    explanation:
      'O viés vem de como a amostra foi escolhida: mesmo grande, ela pode super-representar um grupo.',
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'Por que a mediana costuma ser preferida à média em salários?',
    options: [
      'Porque é mais rápida de calcular',
      'Porque é menos afetada por valores extremos',
      'Porque sempre coincide com a moda',
      'Porque usa todos os valores do conjunto',
    ],
    answer: 1,
    explanation:
      'Alguns salários muito altos puxam a média para cima; a mediana só depende da posição central.',
  },
  {
    theme: 'matematica',
    difficulty: 'dificil',
    prompt: 'O que significa um intervalo de confiança de 95%?',
    options: [
      'Que 95% dos dados estão dentro do intervalo',
      'Que há 95% de chance de o próximo valor cair ali',
      'Que o erro da medição é de 5%',
      'Que o método captura o parâmetro em 95% das amostras possíveis',
    ],
    answer: 3,
    explanation:
      'A confiança é uma propriedade do procedimento repetido, não da probabilidade de um intervalo específico.',
  },

  // ── IA ────────────────────────────────────────────────────────────────────────
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'No aprendizado supervisionado, os dados de treino têm o quê?',
    options: [
      'Apenas entradas',
      'Entradas e respostas esperadas',
      'Apenas respostas',
      'Nenhum rótulo',
    ],
    answer: 1,
    explanation: 'Supervisão significa que cada exemplo vem acompanhado da resposta correta.',
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Agrupar clientes sem rótulos prévios é um problema típico de:',
    options: [
      'Classificação',
      'Regressão',
      'Aprendizado não supervisionado',
      'Aprendizado por reforço',
    ],
    answer: 2,
    explanation: 'Sem rótulos, o algoritmo busca estrutura nos dados — é clusterização.',
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Prever o preço de um imóvel (um número contínuo) é um problema de:',
    options: ['Classificação', 'Regressão', 'Clusterização', 'Redução de dimensionalidade'],
    answer: 1,
    explanation: 'Saída numérica contínua caracteriza regressão; classes discretas seriam classificação.',
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Para que serve separar um conjunto de teste?',
    options: [
      'Para treinar mais rápido',
      'Para medir desempenho em dados nunca vistos',
      'Para aumentar o número de exemplos',
      'Para reduzir o número de atributos',
    ],
    answer: 1,
    explanation: 'Avaliar em dados não usados no treino é o que estima a generalização real.',
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'O que é uma época (epoch) no treinamento de uma rede neural?',
    options: [
      'Uma passagem completa por todo o conjunto de treino',
      'Um único exemplo processado',
      'Uma camada da rede',
      'Um ajuste de taxa de aprendizado',
    ],
    answer: 0,
    explanation: 'Uma época é uma varredura completa do conjunto de treinamento.',
  },
  {
    theme: 'ia',
    difficulty: 'facil',
    prompt: 'Numa rede neural, a função de ativação serve principalmente para:',
    options: [
      'Introduzir não linearidade',
      'Reduzir o número de camadas',
      'Ordenar os dados',
      'Substituir a função de perda',
    ],
    answer: 0,
    explanation: 'Sem não linearidade, empilhar camadas equivaleria a uma única transformação linear.',
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'Um modelo com erro baixo no treino e alto no teste está sofrendo de:',
    options: ['Underfitting', 'Overfitting', 'Falta de dados de teste', 'Vazamento de rótulo'],
    answer: 1,
    explanation: 'Overfitting é decorar o treino sem generalizar para dados novos.',
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'Numa base com 99% de exemplos negativos, por que acurácia engana?',
    options: [
      'Porque a acurácia não é calculável',
      'Porque prever sempre "negativo" já dá 99%',
      'Porque a acurácia ignora os negativos',
      'Porque exige dados balanceados para rodar',
    ],
    answer: 1,
    explanation: 'Em base desbalanceada, um modelo trivial atinge acurácia alta sem acertar a classe rara.',
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'A precisão (precision) de um classificador responde a qual pergunta?',
    options: [
      'Dos positivos reais, quantos achei?',
      'Dos que classifiquei como positivos, quantos acertei?',
      'Quantos exemplos classifiquei ao todo?',
      'Qual o erro médio quadrático?',
    ],
    answer: 1,
    explanation: 'Precisão mede a taxa de acerto entre os itens que o modelo apontou como positivos.',
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'Para que serve a validação cruzada (cross-validation)?',
    options: [
      'Aumentar o tamanho do conjunto de dados',
      'Estimar desempenho de forma mais estável usando várias divisões',
      'Eliminar atributos irrelevantes',
      'Acelerar a convergência do treino',
    ],
    answer: 1,
    explanation: 'Rodar em várias partições reduz a dependência de uma divisão de sorte.',
  },
  {
    theme: 'ia',
    difficulty: 'media',
    prompt: 'Taxa de aprendizado muito alta no gradiente descendente tende a causar:',
    options: [
      'Convergência mais precisa',
      'Oscilação ou divergência da perda',
      'Overfitting garantido',
      'Redução do número de parâmetros',
    ],
    answer: 1,
    explanation: 'Passos grandes demais ultrapassam o mínimo e a perda deixa de cair de forma estável.',
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'O trade-off viés-variância descreve a tensão entre:',
    options: [
      'Velocidade e memória',
      'Simplicidade excessiva e sensibilidade ao ruído',
      'Treino e inferência',
      'Dados rotulados e não rotulados',
    ],
    answer: 1,
    explanation: 'Viés alto simplifica demais; variância alta ajusta ruído. Reduzir um tende a aumentar o outro.',
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'Regularização L2 age sobre o modelo de que forma?',
    options: [
      'Zera completamente pesos irrelevantes',
      'Penaliza pesos grandes, encolhendo-os',
      'Aumenta o número de camadas',
      'Remove exemplos ruidosos do treino',
    ],
    answer: 1,
    explanation: 'L2 adiciona à perda o quadrado dos pesos, empurrando-os para valores menores.',
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'O que caracteriza o vazamento de dados (data leakage)?',
    options: [
      'Perda de exemplos durante o carregamento',
      'Informação do alvo ou do teste influenciando o treino',
      'Uso de dados públicos',
      'Excesso de atributos categóricos',
    ],
    answer: 1,
    explanation: 'Quando o modelo enxerga informação que não teria em produção, a avaliação fica otimista demais.',
  },
  {
    theme: 'ia',
    difficulty: 'dificil',
    prompt: 'No aprendizado por reforço, o agente aprende a partir de:',
    options: [
      'Rótulos corretos para cada ação',
      'Recompensas obtidas ao interagir com o ambiente',
      'Agrupamentos de estados semelhantes',
      'Uma base fixa e imutável',
    ],
    answer: 1,
    explanation: 'O sinal de aprendizado é a recompensa acumulada, não a resposta correta por ação.',
  },

  // ── Robótica ──────────────────────────────────────────────────────────────────
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Qual componente converte energia elétrica em movimento num robô?',
    options: ['Sensor', 'Atuador', 'Microcontrolador', 'Barramento'],
    answer: 1,
    explanation: 'Atuadores, como motores e servos, produzem o movimento do robô.',
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Um sensor ultrassônico é tipicamente usado para medir:',
    options: ['Temperatura', 'Distância até um obstáculo', 'Corrente elétrica', 'Cor de superfície'],
    answer: 1,
    explanation: 'Ele mede o tempo de eco do som refletido para estimar a distância.',
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'O que é um sistema embarcado?',
    options: [
      'Um computador de uso geral',
      'Um sistema computacional dedicado dentro de um equipamento',
      'Um servidor em nuvem',
      'Um protocolo de rede sem fio',
    ],
    answer: 1,
    explanation: 'Embarcado é o computador dedicado a uma função específica dentro de um produto.',
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Quantos graus de liberdade tem um robô que só translada em X e Y?',
    options: ['1', '2', '3', '6'],
    answer: 1,
    explanation: 'Cada eixo independente de movimento conta como um grau de liberdade.',
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'Num servomotor comum, o sinal de controle define principalmente:',
    options: ['A posição angular desejada', 'A tensão da bateria', 'O protocolo de rede', 'A temperatura do motor'],
    answer: 0,
    explanation: 'O servo interpreta a largura de pulso como o ângulo que deve manter.',
  },
  {
    theme: 'robotica',
    difficulty: 'facil',
    prompt: 'O que um encoder acoplado a uma roda normalmente mede?',
    options: ['Rotação e deslocamento', 'Temperatura do eixo', 'Umidade do ar', 'Intensidade luminosa'],
    answer: 0,
    explanation: 'O encoder conta pulsos de rotação, permitindo estimar a distância percorrida.',
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Num controlador PID, o termo integral serve para corrigir:',
    options: [
      'Ruído de alta frequência',
      'Erro acumulado em regime permanente',
      'A taxa de variação do erro',
      'A saturação do atuador',
    ],
    answer: 1,
    explanation: 'A parcela integral acumula o erro ao longo do tempo e elimina o desvio residual.',
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Cinemática direta de um manipulador calcula:',
    options: [
      'Os ângulos das juntas a partir da posição da garra',
      'A posição da garra a partir dos ângulos das juntas',
      'A força necessária em cada junta',
      'O consumo de energia do robô',
    ],
    answer: 1,
    explanation: 'A direta parte das juntas para a pose; o caminho inverso é a cinemática inversa.',
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Por que PWM é usado para controlar a velocidade de um motor DC?',
    options: [
      'Porque altera a frequência da rede',
      'Porque varia a tensão média ligando e desligando rapidamente',
      'Porque converte sinal digital em analógico puro',
      'Porque isola eletricamente o motor',
    ],
    answer: 1,
    explanation: 'Variando a razão entre ligado e desligado, o PWM entrega uma tensão média ajustável.',
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Num sistema de tempo real duro (hard real-time), perder um prazo significa:',
    options: [
      'Apenas degradação de desempenho',
      'Falha do sistema',
      'Reinício automático',
      'Aumento do consumo de energia',
    ],
    answer: 1,
    explanation: 'Em tempo real duro, o prazo faz parte da corretude: perdê-lo é falhar.',
  },
  {
    theme: 'robotica',
    difficulty: 'media',
    prompt: 'Fundir leituras de vários sensores para estimar melhor um estado chama-se:',
    options: ['Amostragem', 'Fusão sensorial', 'Calibração', 'Atuação'],
    answer: 1,
    explanation: 'A fusão sensorial combina fontes ruidosas para produzir uma estimativa mais confiável.',
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'O problema de SLAM em robótica móvel consiste em:',
    options: [
      'Planejar a rota mais curta com mapa conhecido',
      'Mapear o ambiente e se localizar nele simultaneamente',
      'Calibrar sensores antes da operação',
      'Controlar a força de preensão da garra',
    ],
    answer: 1,
    explanation: 'SLAM resolve mapa e localização ao mesmo tempo, sem conhecer nenhum dos dois de início.',
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'Pelo teorema da amostragem, para reconstruir um sinal a taxa deve ser:',
    options: [
      'Igual à maior frequência do sinal',
      'Maior que o dobro da maior frequência',
      'Metade da maior frequência',
      'Independente da frequência',
    ],
    answer: 1,
    explanation: 'É o critério de Nyquist: amostrar abaixo do dobro causa aliasing irreversível.',
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'Numa junta com folga mecânica, o efeito típico no controle é:',
    options: [
      'Aumento da precisão',
      'Zona morta na resposta ao comando',
      'Redução do consumo elétrico',
      'Eliminação de ruído no sensor',
    ],
    answer: 1,
    explanation: 'A folga cria um intervalo em que o comando não produz movimento — a zona morta.',
  },
  {
    theme: 'robotica',
    difficulty: 'dificil',
    prompt: 'Por que uma interrupção é preferível a polling em sistemas embarcados?',
    options: [
      'Porque consome mais CPU e por isso é mais rápida',
      'Porque libera a CPU até o evento realmente ocorrer',
      'Porque dispensa tratamento de concorrência',
      'Porque aumenta a latência de resposta',
    ],
    answer: 1,
    explanation: 'A interrupção evita a espera ativa, deixando a CPU livre até o evento acontecer.',
  },

  // ── Arquitetura ───────────────────────────────────────────────────────────────
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual memória é mais rápida e fica mais próxima do processador?',
    options: ['Disco SSD', 'Memória RAM', 'Cache', 'Fita magnética'],
    answer: 2,
    explanation: 'A cache fica entre o processador e a RAM justamente por ser mais rápida.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Quantos bytes há em 1 KiB (kibibyte)?',
    options: ['1000', '1024', '512', '2048'],
    answer: 1,
    explanation: 'O prefixo binário Ki vale 2¹⁰, ou seja, 1024 bytes.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Qual componente é responsável por executar as instruções de um programa?',
    options: ['A CPU', 'O disco rígido', 'A fonte de alimentação', 'A placa de rede'],
    answer: 0,
    explanation: 'A unidade central de processamento busca, decodifica e executa as instruções.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Na arquitetura de von Neumann, dados e instruções ficam:',
    options: [
      'Em memórias fisicamente separadas',
      'Na mesma memória',
      'Somente em registradores',
      'Apenas em disco',
    ],
    answer: 1,
    explanation: 'Compartilhar a memória é o que distingue von Neumann da arquitetura Harvard.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'O que o sistema operacional faz no escalonamento de processos?',
    options: [
      'Decide qual processo usa a CPU e quando',
      'Compila o código-fonte',
      'Formata o disco',
      'Traduz endereços IP',
    ],
    answer: 0,
    explanation: 'O escalonador reparte o tempo de CPU entre os processos prontos para executar.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'facil',
    prompt: 'Quantos valores distintos um registrador de 8 bits pode armazenar?',
    options: ['8', '64', '128', '256'],
    answer: 3,
    explanation: 'São 2⁸ = 256 combinações possíveis de bits.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Qual a principal diferença entre processo e thread?',
    options: [
      'Threads do mesmo processo compartilham o espaço de memória',
      'Processos são sempre mais rápidos',
      'Threads não podem executar em paralelo',
      'Processos não têm identificador',
    ],
    answer: 0,
    explanation: 'Threads dividem memória do processo; processos têm espaços de endereçamento isolados.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'O pipeline de instruções melhora o desempenho porque:',
    options: [
      'Reduz o número de instruções do programa',
      'Sobrepõe etapas de instruções diferentes',
      'Elimina acessos à memória',
      'Aumenta o tamanho da cache',
    ],
    answer: 1,
    explanation: 'Enquanto uma instrução é decodificada, outra já é buscada — aumenta a vazão.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Para que serve a memória virtual?',
    options: [
      'Aumentar a frequência do processador',
      'Dar a cada processo um espaço de endereços isolado e maior que a RAM',
      'Substituir a cache',
      'Acelerar a placa de vídeo',
    ],
    answer: 1,
    explanation: 'A memória virtual isola processos e permite endereçar mais do que a RAM física.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Um cache miss ocorre quando:',
    options: [
      'O dado buscado não está na cache',
      'A cache está vazia por definição',
      'O processador está ocioso',
      'O disco falha na leitura',
    ],
    answer: 0,
    explanation: 'No miss é preciso buscar o dado num nível mais lento da hierarquia de memória.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'media',
    prompt: 'Uma condição de corrida (race condition) acontece quando:',
    options: [
      'Um processo usa CPU demais',
      'O resultado depende da ordem de execução de threads concorrentes',
      'A memória está fragmentada',
      'O disco está cheio',
    ],
    answer: 1,
    explanation: 'Sem sincronização, a ordem de acesso concorrente muda o resultado final.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Pela Lei de Amdahl, o ganho com paralelismo é limitado principalmente por:',
    options: [
      'A quantidade de memória disponível',
      'A fração sequencial do programa',
      'A velocidade do disco',
      'O número de threads criadas',
    ],
    answer: 1,
    explanation: 'A parte que não paraleliza vira o teto do speedup, por mais núcleos que se acrescente.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Qual condição NÃO é necessária para ocorrer deadlock?',
    options: [
      'Exclusão mútua',
      'Espera circular',
      'Preempção dos recursos',
      'Posse e espera',
    ],
    answer: 2,
    explanation: 'Deadlock exige justamente a AUSÊNCIA de preempção; as outras três são necessárias.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Numa chamada de sistema, por que há troca de modo usuário para kernel?',
    options: [
      'Para liberar mais memória ao processo',
      'Porque operações privilegiadas exigem proteção do hardware',
      'Para acelerar o pipeline',
      'Porque o compilador exige',
    ],
    answer: 1,
    explanation: 'O modo kernel dá acesso a instruções privilegiadas que o modo usuário não pode executar.',
  },
  {
    theme: 'arquitetura',
    difficulty: 'dificil',
    prompt: 'Qual princípio explica por que caches funcionam bem na prática?',
    options: [
      'Localidade temporal e espacial dos acessos',
      'A distribuição uniforme dos endereços',
      'A ausência de laços nos programas',
      'A aleatoriedade das instruções',
    ],
    answer: 0,
    explanation: 'Programas reencostam nos mesmos dados e em vizinhos próximos, o que a cache explora.',
  },

  // ── Engenharia de Software ────────────────────────────────────────────────────
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'Como se chama o documento que descreve o que o sistema deve fazer?',
    options: [
      'Manual do usuário',
      'Especificação de requisitos',
      'Plano de testes',
      'Relatório de entrega',
    ],
    answer: 1,
    explanation:
      'A especificação de requisitos registra o que foi acordado e vira a referência para desenvolver e testar.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'No Scrum, quem prioriza os itens do backlog do produto?',
    options: [
      'O Scrum Master',
      'Qualquer pessoa do time',
      'O Product Owner',
      'O cliente final, diretamente',
    ],
    answer: 2,
    explanation:
      'O Product Owner responde pelo valor entregue e por isso decide a ordem dos itens.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'O que um caso de teste precisa descrever?',
    options: [
      'Só o resultado obtido na execução',
      'Apenas o nome do desenvolvedor responsável',
      'Somente o módulo afetado',
      'Entrada, passos e resultado esperado',
    ],
    answer: 3,
    explanation:
      'Sem resultado esperado não há como dizer se o teste passou: ele vira apenas uma execução.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'O que significa refatorar um código?',
    options: [
      'Melhorar a estrutura interna sem mudar o comportamento',
      'Reescrever o sistema em outra linguagem',
      'Adicionar uma funcionalidade nova',
      'Corrigir um defeito reportado pelo cliente',
    ],
    answer: 0,
    explanation:
      'Refatoração muda como o código está escrito, não o que ele faz — por isso depende de testes.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'Num diagrama de classes da UML, a seta de herança aponta para quê?',
    options: [
      'Para a subclasse',
      'Para a superclasse',
      'Para a classe que instancia',
      'Para o pacote que contém a classe',
    ],
    answer: 1,
    explanation:
      'A generalização aponta do específico para o geral: a subclasse aponta para a superclasse.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'facil',
    prompt: 'O que é code review?',
    options: [
      'A execução automática dos testes na integração',
      'A revisão do código por outra pessoa antes de integrar',
      'A medição de desempenho do sistema',
      'A documentação gerada a partir dos comentários',
    ],
    answer: 1,
    explanation:
      'É uma inspeção humana: pega problemas de projeto e legibilidade que o teste automatizado não vê.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'Em BPMN, o que um círculo de borda fina representa?',
    options: [
      'Um evento de início',
      'Um evento de fim',
      'Uma tarefa manual',
      'Um subprocesso',
    ],
    answer: 0,
    explanation:
      'O início tem borda fina e o fim tem borda grossa — é assim que se lê a direção do fluxo.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'Para que serve um protótipo de baixa fidelidade?',
    options: [
      'Substituir a documentação do sistema',
      'Testar o desempenho sob carga',
      'Validar a ideia cedo e com pouco custo',
      'Entregar o produto final ao cliente',
    ],
    answer: 2,
    explanation:
      'Um rascunho barato permite descobrir que a ideia está errada antes de investir em código.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'O que um teste de integração verifica?',
    options: [
      'Uma função isolada do sistema',
      'A interação entre módulos que já funcionam separados',
      'A aparência da interface em vários navegadores',
      'A ortografia das mensagens exibidas',
    ],
    answer: 1,
    explanation:
      'Muitos defeitos aparecem só na fronteira entre componentes, que o teste unitário não exercita.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'Por que "o sistema deve ser rápido" é um requisito ruim?',
    options: [
      'Porque é um requisito não funcional',
      'Porque não pode ser verificado objetivamente',
      'Porque não menciona a tecnologia usada',
      'Porque deveria estar no manual do usuário',
    ],
    answer: 1,
    explanation:
      'Sem um número não há como testar: "rápido" muda de significado conforme quem lê.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'media',
    prompt: 'O que é manutenção corretiva?',
    options: [
      'Adaptar o sistema a um novo sistema operacional',
      'Acrescentar funcionalidades pedidas depois da entrega',
      'Melhorar o desempenho de uma consulta lenta',
      'Corrigir um defeito encontrado depois da entrega',
    ],
    answer: 3,
    explanation:
      'Corretiva conserta defeito; adaptativa acompanha mudanças de ambiente; evolutiva acrescenta recurso.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'Qual combinação de acoplamento e coesão é desejável num projeto?',
    options: [
      'Alto acoplamento e alta coesão',
      'Baixo acoplamento e alta coesão',
      'Baixo acoplamento e baixa coesão',
      'Alto acoplamento e baixa coesão',
    ],
    answer: 1,
    explanation:
      'Módulos com responsabilidade clara (coesos) e pouca dependência entre si são fáceis de mudar isoladamente.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt:
      'Num diagrama de casos de uso, o que o relacionamento «include» indica?',
    options: [
      'Um comportamento opcional, ativado por condição',
      'Uma herança entre dois atores',
      'Um comportamento obrigatório reaproveitado por outro caso de uso',
      'A ordem em que os casos de uso são executados',
    ],
    answer: 2,
    explanation:
      'O «include» sempre ocorre; o opcional é o «extend», que depende de um ponto de extensão.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'O que caracteriza a prática de integração contínua?',
    options: [
      'Publicar uma versão em produção toda semana',
      'Manter uma branch por desenvolvedor até o fim do projeto',
      'Revisar o código só antes da entrega final',
      'Integrar e testar o código com frequência, em build automatizado',
    ],
    answer: 3,
    explanation:
      'Integrar em pequenos passos torna cada conflito pequeno e revela a quebra no mesmo dia em que ela aparece.',
  },
  {
    theme: 'engenharia-software',
    difficulty: 'dificil',
    prompt: 'O que diferencia um modelo incremental do modelo cascata?',
    options: [
      'O incremental entrega partes utilizáveis a cada ciclo',
      'O incremental dispensa levantamento de requisitos',
      'O cascata não prevê fase de testes',
      'O cascata exige equipes maiores',
    ],
    answer: 0,
    explanation:
      'Entregar em fatias permite corrigir o rumo com feedback real, em vez de descobrir o erro só no fim.',
  },

  // ── Redes ─────────────────────────────────────────────────────────────────────
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual protocolo garante entrega ordenada e confiável dos dados?',
    options: ['UDP', 'TCP', 'ICMP', 'ARP'],
    answer: 1,
    explanation: 'O TCP confirma recebimento, retransmite perdas e reordena segmentos.',
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Para que serve o DNS?',
    options: [
      'Atribuir endereços IP automaticamente',
      'Traduzir nomes de domínio em endereços IP',
      'Criptografar o tráfego',
      'Rotear pacotes entre redes',
    ],
    answer: 1,
    explanation: 'O DNS resolve nomes legíveis para os endereços numéricos usados no roteamento.',
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual porta é usada por padrão pelo HTTPS?',
    options: ['21', '80', '443', '8080'],
    answer: 2,
    explanation: 'HTTPS usa a porta 443; a 80 é do HTTP sem criptografia.',
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Quantos bits tem um endereço IPv4?',
    options: ['16', '32', '64', '128'],
    answer: 1,
    explanation: 'IPv4 usa 32 bits, escritos como quatro octetos decimais.',
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Qual serviço distribui endereços IP automaticamente numa rede local?',
    options: ['DNS', 'DHCP', 'NAT', 'FTP'],
    answer: 1,
    explanation: 'O DHCP concede endereços e parâmetros de rede aos dispositivos que se conectam.',
  },
  {
    theme: 'redes',
    difficulty: 'facil',
    prompt: 'Um código de status HTTP 404 indica:',
    options: [
      'Erro interno do servidor',
      'Recurso não encontrado',
      'Requisição bem-sucedida',
      'Acesso não autorizado',
    ],
    answer: 1,
    explanation: 'A família 4xx indica erro do cliente; 404 é especificamente recurso inexistente.',
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Qual a principal diferença entre TCP e UDP?',
    options: [
      'UDP é mais lento que TCP',
      'TCP garante entrega e ordem; UDP não',
      'UDP criptografa os dados',
      'TCP não usa portas',
    ],
    answer: 1,
    explanation: 'UDP troca as garantias por menor latência e menos overhead.',
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Em qual camada do modelo OSI atua um switch tradicional?',
    options: ['Física', 'Enlace', 'Rede', 'Aplicação'],
    answer: 1,
    explanation: 'O switch comuta quadros usando endereços MAC, que pertencem à camada de enlace.',
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'O que o NAT faz numa rede doméstica?',
    options: [
      'Traduz endereços privados em um endereço público',
      'Resolve nomes de domínio',
      'Criptografa o tráfego de saída',
      'Distribui endereços IP',
    ],
    answer: 0,
    explanation: 'O NAT permite vários dispositivos internos compartilharem um único IP público.',
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'Numa máscara /24, quantos endereços de host utilizáveis existem?',
    options: ['254', '256', '128', '512'],
    answer: 0,
    explanation: 'São 256 endereços, menos o de rede e o de broadcast, restando 254 utilizáveis.',
  },
  {
    theme: 'redes',
    difficulty: 'media',
    prompt: 'O que caracteriza o HTTP como protocolo sem estado (stateless)?',
    options: [
      'Não usa TCP',
      'Cada requisição é independente das anteriores',
      'Não permite autenticação',
      'Não aceita cabeçalhos',
    ],
    answer: 1,
    explanation: 'O servidor não guarda contexto entre requisições; daí a necessidade de cookies ou tokens.',
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Qual é o propósito do handshake de três vias do TCP?',
    options: [
      'Criptografar a conexão',
      'Sincronizar números de sequência e estabelecer a conexão',
      'Comprimir os dados',
      'Escolher a rota dos pacotes',
    ],
    answer: 1,
    explanation: 'SYN, SYN-ACK e ACK acertam os números de sequência iniciais dos dois lados.',
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'O que o TTL de um pacote IP evita?',
    options: [
      'Perda de pacotes por congestionamento',
      'Que pacotes circulem indefinidamente em loops de roteamento',
      'Fragmentação excessiva',
      'Ataques de negação de serviço',
    ],
    answer: 1,
    explanation: 'Cada salto decrementa o TTL; ao zerar, o pacote é descartado e o loop se encerra.',
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'No TLS, para que serve o certificado apresentado pelo servidor?',
    options: [
      'Comprimir o tráfego',
      'Vincular a identidade do servidor a uma chave pública, atestada por uma AC',
      'Acelerar o handshake',
      'Substituir o DNS',
    ],
    answer: 1,
    explanation: 'O certificado prova que aquela chave pública pertence àquele domínio, segundo uma autoridade.',
  },
  {
    theme: 'redes',
    difficulty: 'dificil',
    prompt: 'Por que WebSocket é preferível a polling para atualizações em tempo real?',
    options: [
      'Porque usa UDP em vez de TCP',
      'Porque mantém uma conexão bidirecional aberta, sem repetir requisições',
      'Porque dispensa autenticação',
      'Porque comprime automaticamente os dados',
    ],
    answer: 1,
    explanation: 'A conexão persistente elimina o custo de abrir requisições repetidas para perguntar por novidades.',
  },

  // ── Banco de Dados ────────────────────────────────────────────────────────────
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual comando SQL recupera dados de uma tabela?',
    options: ['INSERT', 'SELECT', 'UPDATE', 'DELETE'],
    answer: 1,
    explanation: 'SELECT é o comando de consulta; os outros modificam os dados.',
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'O que é uma chave primária?',
    options: [
      'Um campo que identifica unicamente cada linha',
      'Um campo que aponta para outra tabela',
      'Um índice opcional para acelerar buscas',
      'Um campo sempre numérico',
    ],
    answer: 0,
    explanation: 'A chave primária garante unicidade e não aceita valor nulo.',
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual cláusula SQL filtra linhas antes do agrupamento?',
    options: ['HAVING', 'WHERE', 'ORDER BY', 'GROUP BY'],
    answer: 1,
    explanation: 'WHERE filtra linhas individuais; HAVING filtra grupos já formados.',
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'O que uma chave estrangeira representa?',
    options: [
      'Uma referência a uma chave de outra tabela',
      'Um campo criptografado',
      'Um índice único',
      'Um campo calculado',
    ],
    answer: 0,
    explanation: 'A chave estrangeira liga tabelas e mantém a integridade referencial.',
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Qual função SQL conta o número de linhas de um resultado?',
    options: ['SUM()', 'COUNT()', 'AVG()', 'MAX()'],
    answer: 1,
    explanation: 'COUNT() retorna a quantidade de linhas que satisfazem a consulta.',
  },
  {
    theme: 'banco',
    difficulty: 'facil',
    prompt: 'Num banco relacional, uma tabela é composta por:',
    options: ['Linhas e colunas', 'Nós e arestas', 'Chaves e valores', 'Documentos aninhados'],
    answer: 0,
    explanation: 'O modelo relacional organiza dados em relações — tabelas de linhas e colunas.',
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Qual a diferença entre INNER JOIN e LEFT JOIN?',
    options: [
      'LEFT JOIN mantém linhas da tabela da esquerda sem correspondência',
      'INNER JOIN é sempre mais lento',
      'LEFT JOIN só funciona com chave primária',
      'Não há diferença prática',
    ],
    answer: 0,
    explanation: 'O LEFT JOIN preserva as linhas da esquerda, preenchendo com nulo o que não casa.',
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'No acrônimo ACID, o "A" de atomicidade significa que a transação:',
    options: [
      'Executa em paralelo com outras',
      'Ocorre inteira ou não ocorre',
      'Persiste após falha de energia',
      'Mantém as regras de integridade',
    ],
    answer: 1,
    explanation: 'Atomicidade impede estados intermediários: ou tudo é aplicado, ou nada é.',
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Para que serve um índice numa tabela?',
    options: [
      'Reduzir o espaço em disco',
      'Acelerar buscas ao custo de escritas mais caras',
      'Garantir unicidade sempre',
      'Substituir a chave primária',
    ],
    answer: 1,
    explanation: 'O índice troca espaço e custo de escrita por leitura mais rápida.',
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'A primeira forma normal (1FN) exige que:',
    options: [
      'Não existam dependências transitivas',
      'Os valores dos atributos sejam atômicos',
      'Toda tabela tenha índice',
      'Não haja chaves estrangeiras',
    ],
    answer: 1,
    explanation: 'A 1FN elimina grupos repetitivos, exigindo um único valor por célula.',
  },
  {
    theme: 'banco',
    difficulty: 'media',
    prompt: 'Em SQL, comparar um campo com NULL usando "= NULL" retorna:',
    options: ['Verdadeiro se for nulo', 'Falso sempre', 'Desconhecido (nunca verdadeiro)', 'Erro de sintaxe'],
    answer: 2,
    explanation: 'NULL é ausência de valor; a comparação exige IS NULL em vez do operador de igualdade.',
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'O que caracteriza uma leitura suja (dirty read)?',
    options: [
      'Ler dados de uma transação ainda não confirmada',
      'Ler dados de uma tabela sem índice',
      'Ler a mesma linha duas vezes',
      'Ler dados criptografados',
    ],
    answer: 0,
    explanation: 'A leitura suja expõe alterações que podem sofrer rollback e nunca existir de fato.',
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Pelo teorema CAP, num sistema distribuído sob partição de rede escolhe-se entre:',
    options: [
      'Consistência e disponibilidade',
      'Velocidade e custo',
      'Segurança e desempenho',
      'Escrita e leitura',
    ],
    answer: 0,
    explanation: 'Havendo partição, é preciso sacrificar consistência forte ou disponibilidade.',
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'O que é o problema N+1 em consultas?',
    options: [
      'Uma consulta que retorna uma linha a mais',
      'Uma consulta inicial seguida de uma consulta por resultado, em laço',
      'Índice com uma coluna a mais que o necessário',
      'Transação com um commit extra',
    ],
    answer: 1,
    explanation: 'Buscar relacionados um a um multiplica idas ao banco; a saída é carregar em lote com join.',
  },
  {
    theme: 'banco',
    difficulty: 'dificil',
    prompt: 'Por que consultas parametrizadas previnem injeção de SQL?',
    options: [
      'Porque criptografam a consulta',
      'Porque separam o código SQL dos dados, que nunca são interpretados como comando',
      'Porque limitam o tamanho da entrada',
      'Porque removem aspas automaticamente',
    ],
    answer: 1,
    explanation: 'O plano da consulta é fixado antes dos valores chegarem, então o dado não vira comando.',
  },

  // ── Algoritmos ────────────────────────────────────────────────────────────────
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual estrutura de dados segue a política "último a entrar, primeiro a sair"?',
    options: ['Fila', 'Pilha', 'Lista ligada', 'Árvore'],
    answer: 1,
    explanation: 'A pilha (LIFO) remove sempre o elemento inserido mais recentemente.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual estrutura segue a política "primeiro a entrar, primeiro a sair"?',
    options: ['Pilha', 'Fila', 'Heap', 'Grafo'],
    answer: 1,
    explanation: 'A fila (FIFO) atende na ordem de chegada.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual é a complexidade de acessar um elemento por índice num vetor?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 0,
    explanation: 'O endereço é calculado diretamente a partir do índice, em tempo constante.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Uma busca binária exige que o vetor esteja:',
    options: ['Ordenado', 'Sem repetições', 'Com tamanho par', 'Preenchido com inteiros'],
    answer: 0,
    explanation: 'A cada passo a busca descarta metade do intervalo, o que só vale se houver ordem.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Toda função recursiva precisa ter obrigatoriamente:',
    options: [
      'Um caso base',
      'Dois parâmetros',
      'Um laço interno',
      'Retorno numérico',
    ],
    answer: 0,
    explanation: 'Sem caso base a recursão não termina e estoura a pilha.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual a complexidade de percorrer todos os elementos de uma lista de n itens?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 2,
    explanation: 'Visitar cada elemento uma vez custa tempo proporcional ao tamanho da lista.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a complexidade média do quicksort?',
    options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    answer: 1,
    explanation: 'Em média as partições são equilibradas; o pior caso O(n²) ocorre com pivô ruim.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Numa tabela hash, o que é uma colisão?',
    options: [
      'Duas chaves mapeadas para a mesma posição',
      'Uma chave sem valor associado',
      'Uma tabela cheia',
      'Uma busca malsucedida',
    ],
    answer: 0,
    explanation: 'Como o espaço de saída é menor que o de chaves, colisões são inevitáveis e precisam de tratamento.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'A busca em largura (BFS) num grafo usa qual estrutura auxiliar?',
    options: ['Pilha', 'Fila', 'Heap', 'Tabela hash'],
    answer: 1,
    explanation: 'A fila garante visitar os vértices em ordem crescente de distância da origem.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Numa árvore binária de busca balanceada, a busca custa:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 1,
    explanation: 'A cada nível descarta-se metade da árvore, e a altura balanceada é logarítmica.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'O que caracteriza um algoritmo guloso (greedy)?',
    options: [
      'Testa todas as combinações possíveis',
      'Escolhe o melhor local a cada passo, sem revisar decisões',
      'Divide o problema ao meio recursivamente',
      'Memoriza subproblemas resolvidos',
    ],
    answer: 1,
    explanation: 'O guloso decide localmente e nunca volta atrás — nem sempre chega ao ótimo global.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'O que a programação dinâmica explora para ser eficiente?',
    options: [
      'Aleatoriedade das entradas',
      'Subproblemas sobrepostos e subestrutura ótima',
      'Ordenação prévia dos dados',
      'Paralelismo do processador',
    ],
    answer: 1,
    explanation: 'Resolver cada subproblema uma vez e reutilizar o resultado é o que corta o custo exponencial.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Um algoritmo de ordenação estável garante que:',
    options: [
      'O tempo de execução não varia',
      'Elementos de mesma chave preservam a ordem relativa original',
      'Não usa memória extra',
      'Funciona apenas com inteiros',
    ],
    answer: 1,
    explanation: 'Estabilidade importa ao ordenar por múltiplos critérios em sequência.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Por que o algoritmo de Dijkstra não funciona com arestas de peso negativo?',
    options: [
      'Porque não consegue representar números negativos',
      'Porque assume que um vértice finalizado não pode ter caminho menor depois',
      'Porque exige grafo não direcionado',
      'Porque a fila de prioridade não aceita negativos',
    ],
    answer: 1,
    explanation: 'Uma aresta negativa poderia melhorar um caminho já dado como definitivo.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'O que significa dizer que um problema está em NP?',
    options: [
      'Que não tem solução',
      'Que uma solução proposta pode ser verificada em tempo polinomial',
      'Que exige tempo exponencial obrigatoriamente',
      'Que só pode ser resolvido por aproximação',
    ],
    answer: 1,
    explanation: 'NP é definido pela verificação eficiente de um certificado, não pela dificuldade de achá-lo.',
  },

  // Vindas do tema Lógica, que saiu da roda: dedução, tabela-verdade e
  // raciocínio formal passaram a contar como Algoritmos. O tema fica com o
  // dobro das outras — pool maior não muda nada para o aluno, que sorteia uma
  // questão por vez.
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Se p é verdadeiro e q é falso, qual o valor de "p E q"?',
    options: ['Verdadeiro', 'Falso', 'Indefinido', 'Depende de p'],
    answer: 1,
    explanation: 'A conjunção só é verdadeira quando as duas partes são verdadeiras.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Quantas linhas tem a tabela-verdade de uma fórmula com 3 variáveis?',
    options: ['3', '6', '8', '9'],
    answer: 2,
    explanation: 'São 2³ = 8 combinações possíveis de verdadeiro e falso.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Qual operador lógico resulta em verdadeiro quando pelo menos uma das partes é verdadeira?',
    options: ['E (conjunção)', 'OU (disjunção)', 'NÃO (negação)', 'SE-ENTÃO'],
    answer: 1,
    explanation: 'A disjunção só é falsa quando ambas as partes são falsas.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'A negação de "x > 10" é:',
    options: ['x < 10', 'x <= 10', 'x >= 10', 'x != 10'],
    answer: 1,
    explanation: 'Negar "maior que" inclui o caso de igualdade, virando "menor ou igual".',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'Numa estrutura "se... senão", quantos dos dois blocos executam numa passagem?',
    options: ['Sempre os dois', 'Exatamente um', 'Nenhum', 'Depende do laço'],
    answer: 1,
    explanation: 'A condição escolhe um dos caminhos; o outro é ignorado naquela passagem.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'facil',
    prompt: 'O que a negação dupla "NÃO (NÃO p)" equivale?',
    options: ['p', 'NÃO p', 'Sempre verdadeiro', 'Sempre falso'],
    answer: 0,
    explanation: 'Negar duas vezes devolve o valor original da proposição.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Pela lei de De Morgan, "NÃO (p E q)" é equivalente a:',
    options: [
      'NÃO p E NÃO q',
      'NÃO p OU NÃO q',
      'p OU q',
      'NÃO p SE-ENTÃO q',
    ],
    answer: 1,
    explanation: 'De Morgan troca a conjunção por disjunção e nega cada parte.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'A implicação "p → q" é falsa em qual único caso?',
    options: [
      'p falso e q falso',
      'p falso e q verdadeiro',
      'p verdadeiro e q falso',
      'p verdadeiro e q verdadeiro',
    ],
    answer: 2,
    explanation: 'Uma promessa só é quebrada quando a hipótese vale e a conclusão falha.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Qual é a contrapositiva de "se chove, então a rua molha"?',
    options: [
      'Se a rua molha, então chove',
      'Se não chove, então a rua não molha',
      'Se a rua não molha, então não chove',
      'Se chove, então a rua não molha',
    ],
    answer: 2,
    explanation: 'A contrapositiva inverte e nega os dois lados, e é sempre equivalente.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Uma fórmula que é verdadeira para toda atribuição de valores chama-se:',
    options: ['Contradição', 'Tautologia', 'Contingência', 'Falácia'],
    answer: 1,
    explanation: 'Tautologia é a fórmula verdadeira em todas as linhas da tabela-verdade.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'media',
    prompt: 'Em "curto-circuito", por que `a != null && a.b` não quebra quando a é nulo?',
    options: [
      'A linguagem ignora erros de nulo',
      'A segunda parte só é avaliada se a primeira for verdadeira',
      'O operador && converte nulo em falso',
      'A ordem das partes não importa',
    ],
    answer: 1,
    explanation: 'A avaliação em curto-circuito para assim que o resultado já está decidido.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Qual conjunto de operadores é suficiente para expressar qualquer função booleana?',
    options: ['Apenas E', 'Apenas OU', 'E junto com NÃO', 'Apenas SE-ENTÃO'],
    answer: 2,
    explanation: 'Conjunção com negação é funcionalmente completo; por De Morgan gera a disjunção.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'A negação de "existe x tal que P(x)" é:',
    options: [
      'Existe x tal que não P(x)',
      'Para todo x, não P(x)',
      'Não existe x tal que não P(x)',
      'Para todo x, P(x)',
    ],
    answer: 1,
    explanation: 'Negar um existencial troca o quantificador para universal e nega o predicado.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'O operador XOR entre p e q é verdadeiro quando:',
    options: [
      'Os dois são verdadeiros',
      'Os dois são falsos',
      'Os valores são diferentes entre si',
      'Pelo menos um é verdadeiro',
    ],
    answer: 2,
    explanation: 'O ou-exclusivo indica divergência: verdadeiro apenas quando os valores diferem.',
  },
  {
    theme: 'algoritmos',
    difficulty: 'dificil',
    prompt: 'Um argumento válido com premissas verdadeiras garante o quê sobre a conclusão?',
    options: [
      'Que ela é verdadeira',
      'Que ela é falsa',
      'Nada, validade é só sobre a forma',
      'Que ela é provável',
    ],
    answer: 0,
    explanation: 'Validade preserva verdade: premissas verdadeiras em forma válida forçam conclusão verdadeira.',
  },
];
